-- psy.market Slice MP-4-G ROLLBACK VERIFY — owner-run read-only exact source proof.
begin transaction isolation level repeatable read read only;
set local row_security=off;set local lock_timeout='5s';set local statement_timeout='30s';
lock table public.profiles,public.listings,public.conversations,public.messages,public.conversation_participant_state in share mode;
with f as(select p.proname,regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')args,p.proowner::regrole::text owner,l.lanname,p.provolatile::text volatility,p.prosecdef,p.proisstrict,p.proleakproof,p.proparallel::text parallel,p.pronargdefaults,coalesce((select string_agg(case when cfg in('search_path=','search_path=""')then'search_path=<empty>'else cfg end,','order by cfg collate "C")from unnest(coalesce(p.proconfig,array[]::text[]))cfg),'<none>')settings,regexp_replace(pg_get_function_result(p.oid),'public\.','','g')result,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g')))body_hash from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public'and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation','unhide_conversation_for_message_recipient','update_conversation_last_message')),
e(proname,args,owner,lanname,volatility,prosecdef,proisstrict,proleakproof,parallel,pronargdefaults,settings,result,body_hash)as(values
 ('append_unread_for','conv_id uuid, profile_id text','postgres','plpgsql','v',true,false,false,'u',0,'search_path=pg_catalog, public, auth','void','6023d0d555a24427a1d98f92d9d37e25'),('find_and_unhide_conversation','target_other_profile_id uuid, target_listing_id uuid','postgres','plpgsql','v',true,false,false,'u',1,'search_path=pg_catalog, public, auth','uuid','ad6475d6ac60d2fe451597dbe78c2453'),('hide_conversation','target_conversation_id uuid','postgres','plpgsql','v',true,false,false,'u',0,'search_path=pg_catalog, public, auth','void','4e5756391924dc30ca09f7b535d36afa'),('remove_unread_for','conv_id uuid, profile_id text','postgres','plpgsql','v',true,false,false,'u',0,'search_path=pg_catalog, public, auth','void','ca52e0ea7f804024cf6f9f7955dc9a62'),('unhide_conversation','target_conversation_id uuid','postgres','plpgsql','v',true,false,false,'u',0,'search_path=pg_catalog, public, auth','void','7e7d2ce7d7cef459c1dd9a72a2eb87ab'),('unhide_conversation_for_message_recipient','','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','trigger','65000503f5c585632d5cae3282217b43'),('update_conversation_last_message','','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','trigger','396ba90811a1f9ba79cbdf3bc3f5b060')),
fa as(select p.proname,a.grantor::regrole::text grantor,case when a.grantee=0 then'PUBLIC'else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a where n.nspname='public'and p.proname in(select proname from e)),
ea(proname,grantor,grantee,privilege_type,is_grantable)as(select name,'postgres',r,'EXECUTE',false from unnest(array['append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation'])name cross join unnest(array['authenticated','postgres','service_role'])r union all select name,'postgres',r,'EXECUTE',false from unnest(array['unhide_conversation_for_message_recipient','update_conversation_last_message'])name cross join unnest(array['postgres','service_role'])r),
d as(select md5(string_agg(proname||'|'||args||'|'||owner||'|'||lanname||'|'||volatility||'|'||prosecdef||'|'||proisstrict||'|'||proleakproof||'|'||parallel||'|'||pronargdefaults||'|'||settings||'|'||result||'|'||body_hash,E'\n'order by proname collate "C",args collate "C"))function_md5 from f),ad as(select md5(string_agg(proname||'|'||grantor||'|'||grantee||'|'||privilege_type||'|'||is_grantable,E'\n'order by proname collate "C",grantor collate "C",grantee collate "C",privilege_type collate "C"))acl_md5 from fa),
checks(name,ok)as(values('owner_context',current_user='postgres'and session_user='postgres'and(select rolsuper or rolbypassrls from pg_roles where rolname=current_user)),('source_functions_exact',not exists((select * from f except select * from e)union all(select * from e except select * from f))),('source_acls_exact',not exists((select * from fa except select * from ea)union all(select * from ea except select * from fa))),('source_digests_exact',(select function_md5='beb07708dde639568ddf4453b01f620d'from d)and(select acl_md5='242b692562ac92d341d6e3b832285a75'from ad)),('post_f_policy_retained',(select count(*)=5 and count(*)filter(where(coalesce(pg_get_expr(polqual,polrelid,false),'')||coalesce(pg_get_expr(polwithcheck,polrelid,false),''))like'%current_active_profile_id%')=5 from pg_policy where polrelid in('public.conversations'::regclass,'public.messages'::regclass,'public.conversation_participant_state'::regclass))),('post_e_foundation_retained',(select count(*)=3 from pg_attribute where attrelid in('public.conversations'::regclass,'public.messages'::regclass)and attname in('buyer_profile_id','seller_profile_id','sender_profile_id')and not attnotnull)and(select count(*)=4 from pg_trigger where not tgisinternal and(tgrelid,tgname)in(('public.conversations'::regclass,'conversations_guard_participants'),('public.conversations'::regclass,'conversations_guard_unread'),('public.messages'::regclass,'messages_guard_active_participant'),('public.conversation_participant_state'::regclass,'conversation_participant_state_guard')))),('trigger_bindings_retained',(select count(*)=2 from pg_trigger where not tgisinternal and(tgrelid,tgname)in(('public.messages'::regclass,'messages_unhide_recipient_conversation'),('public.messages'::regclass,'on_message_insert')))))
select 'SLICE_MP4_G_ROLLBACK_VERIFY'package,case when bool_and(ok)then'GO'else'STOP'end verdict,count(*)filter(where ok)::int passed,count(*)::int total,coalesce(array_agg(name order by name collate "C")filter(where not ok),'{}'::text[])findings,(select function_md5 from d)restored_function_md5,'beb07708dde639568ddf4453b01f620d'expected_function_md5,(select acl_md5 from ad)restored_acl_md5,'242b692562ac92d341d6e3b832285a75'expected_acl_md5,'Exact post-F source RPC/trigger bytes and ACLs restored; F/E state retained. Rollback order remains G before F before E.'::text boundary from checks;
rollback;
