-- psy.market Slice MP-4-F VERIFY — owner-run, read-only target proof.
-- Plain policy rendering only; every LIVE_PIN/digest is wingman-recomputed.
-- Post-F active-authority policy fact: exactly 23 = 13 social/event + 5 profile/listing
-- + 5 conversation. The historical mp4-policy-conversion-verify.sql intentionally STOPs
-- post-F because it pins the superseded ownership expressions.
begin transaction isolation level repeatable read read only;
set local row_security=off;
set local lock_timeout='5s';
set local statement_timeout='30s';
lock table public.profiles,public.listings,public.conversations,public.messages,
 public.conversation_participant_state in share mode;

select 'TARGET_POLICY_ROW' record_type,c.relname table_name,p.polname,p.polcmd::text command,p.polpermissive,
 array(select case when r=0 then 'PUBLIC' else r::regrole::text end from unnest(p.polroles) r order by (case when r=0 then 'PUBLIC' else r::regrole::text end) collate "C") roles,
 lower(regexp_replace(regexp_replace(coalesce(pg_get_expr(p.polqual,p.polrelid,false),''),'public\.','','g'),'[[:space:]]+','','g')) using_expr,
 lower(regexp_replace(regexp_replace(coalesce(pg_get_expr(p.polwithcheck,p.polrelid,false),''),'public\.','','g'),'[[:space:]]+','','g')) check_expr
from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and c.relname in('conversations','messages','conversation_participant_state')
order by c.relname collate "C",p.polname collate "C";

select 'TABLE_ACL_ROW' record_type,c.relname table_name,a.grantor::regrole::text grantor,
 case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable
from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a
where n.nspname='public' and c.relname in('conversations','messages','conversation_participant_state')
order by c.relname collate "C",(a.grantor::regrole::text) collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C";

do $assert$
declare failures text;
begin
 with policies as(
  select c.relname table_name,p.polname,p.polcmd::text command,p.polpermissive,p.polroles,
   lower(regexp_replace(regexp_replace(coalesce(pg_get_expr(p.polqual,p.polrelid,false),''),'public\.','','g'),'[[:space:]]+','','g')) using_expr,
   lower(regexp_replace(regexp_replace(coalesce(pg_get_expr(p.polwithcheck,p.polrelid,false),''),'public\.','','g'),'[[:space:]]+','','g')) check_expr
  from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public' and c.relname in('conversations','messages','conversation_participant_state')
 ),expected_policies(table_name,polname,command,polpermissive,polroles,using_expr,check_expr) as(values
  ('conversation_participant_state','Participants read own conversation state','r',true,array['authenticated'::regrole::oid],'(profile_id=(selectcurrent_active_profile_id()ascurrent_active_profile_id))',''),
  ('conversations','Unbanned buyers create conversations','a',true,array['authenticated'::regrole::oid],'','((notcurrent_user_is_banned())and(buyer_profile_id=(selectcurrent_active_profile_id()ascurrent_active_profile_id))and(buyer_profile_idisnotnull)and(seller_profile_idisnotnull)and(buyer_profile_id<>seller_profile_id)and(notcurrent_user_owns_profile(seller_profile_id))and((listing_idisnull)or(seller_profile_id=(selectl.profile_idfromlistingslwhere(l.id=conversations.listing_id)))))'),
  ('conversations','participants view visible conversations','r',true,array['authenticated'::regrole::oid],'(((buyer_profile_id=(selectcurrent_active_profile_id()ascurrent_active_profile_id))or(seller_profile_id=(selectcurrent_active_profile_id()ascurrent_active_profile_id)))and(not(exists(select1fromconversation_participant_stateswhere((s.conversation_id=conversations.id)and(s.profile_id=(selectcurrent_active_profile_id()ascurrent_active_profile_id))and(s.hidden_atisnotnull))))))',''),
  ('messages','Unbanned participants send messages','a',true,array['authenticated'::regrole::oid],'','((notcurrent_user_is_banned())and(sender_profile_id=(selectcurrent_active_profile_id()ascurrent_active_profile_id))and(exists(select1fromconversationscwhere((c.id=messages.conversation_id)and(c.buyer_profile_idisnotnull)and(c.seller_profile_idisnotnull)and(c.buyer_profile_id<>c.seller_profile_id)and((messages.sender_profile_id=c.buyer_profile_id)or(messages.sender_profile_id=c.seller_profile_id))and(notcurrent_user_owns_profile(casewhen(messages.sender_profile_id=c.buyer_profile_id)thenc.seller_profile_idelsec.buyer_profile_idend))))))'),
  ('messages','participants view messages','r',true,array['authenticated'::regrole::oid],'(exists(select1fromconversationscwhere((c.id=messages.conversation_id)and((c.buyer_profile_id=(selectcurrent_active_profile_id()ascurrent_active_profile_id))or(c.seller_profile_id=(selectcurrent_active_profile_id()ascurrent_active_profile_id))))))','')
 ),helper_state as(
  select n.nspname,p.proname,regexp_replace(pg_get_function_identity_arguments(p.oid),'(public|private)\.','','g') args,p.proowner::regrole::text owner,l.lanname,p.provolatile::text volatility,p.prosecdef,p.proisstrict,p.proleakproof,p.proparallel::text parallel,p.pronargdefaults,
   coalesce((select string_agg(case when cfg in('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by cfg collate "C") from unnest(coalesce(p.proconfig,array[]::text[])) cfg),'<none>') settings,regexp_replace(pg_get_function_result(p.oid),'(public|private)\.','','g') result,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g'))) body_hash
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where (n.nspname='private' and p.proname='current_active_profile_id') or(n.nspname='public' and p.proname in('current_active_profile_id','current_user_owns_profile','current_user_is_banned'))
 ),expected_helper_state(nspname,proname,args,owner,lanname,volatility,prosecdef,proisstrict,proleakproof,parallel,pronargdefaults,settings,result,body_hash) as(values
  ('private','current_active_profile_id','','postgres','plpgsql','s',true,false,false,'u',0,'search_path=<empty>','uuid','8ab19811ddcf117a757e7663efc5ac77'),('public','current_active_profile_id','','postgres','sql','s',true,false,false,'u',0,'search_path=<empty>','uuid','6f6b53dbd223db8ba168073c196f7b1a'),('public','current_user_owns_profile','target_profile_id uuid','postgres','sql','s',true,false,false,'u',0,'search_path=<empty>','boolean','b18b8e4f01df72097d092352423ab8af'),('public','current_user_is_banned','','postgres','sql','s',true,false,false,'u',0,'search_path=pg_catalog, public, auth','boolean','682d0a1d82cd433e5bd7deb4aeee5ede')
 ),helper_acl as(select n.nspname||'.'||p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'(public|private)\.','','g')||')' object_name,a.grantor::regrole::text grantor,case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where(n.nspname='private' and p.proname='current_active_profile_id')or(n.nspname='public' and p.proname in('current_active_profile_id','current_user_owns_profile','current_user_is_banned'))),
 expected_helper_acl(object_name,grantor,grantee,privilege_type,is_grantable) as(values('private.current_active_profile_id()','postgres','postgres','EXECUTE',false),('public.current_active_profile_id()','postgres','authenticated','EXECUTE',false),('public.current_active_profile_id()','postgres','postgres','EXECUTE',false),('public.current_user_owns_profile(target_profile_id uuid)','postgres','authenticated','EXECUTE',false),('public.current_user_owns_profile(target_profile_id uuid)','postgres','postgres','EXECUTE',false),('public.current_user_is_banned()','postgres','authenticated','EXECUTE',false),('public.current_user_is_banned()','postgres','postgres','EXECUTE',false),('public.current_user_is_banned()','postgres','service_role','EXECUTE',false)),
 checks(name,ok,detail) as(values
  ('owner_complete_context',current_user='postgres' and session_user='postgres' and (select rolsuper or rolbypassrls from pg_roles where rolname=current_user),'LIVE_PIN owner completeness'),
  ('five_target_policies_exact',not exists((select * from policies except select * from expected_policies) union all(select * from expected_policies except select * from policies)),'LIVE_PIN bidirectional exact plain-render target expressions'),
  ('authorization_helpers_exact',not exists((select * from helper_state except select * from expected_helper_state)union all(select * from expected_helper_state except select * from helper_state))and not exists((select * from helper_acl except select * from expected_helper_acl)union all(select * from expected_helper_acl except select * from helper_acl)),'full active/ownership/ban helper definitions and ACLs'),
  ('sole_profile_fallback_index_exact',exists(select 1 from pg_index i where i.indexrelid=to_regclass('public.profiles_one_per_user_key')and i.indrelid=to_regclass('public.profiles')and i.indisunique and not i.indisprimary and i.indisvalid and i.indisready and i.indpred is null and pg_get_indexdef(i.indexrelid)='CREATE UNIQUE INDEX profiles_one_per_user_key ON public.profiles USING btree (user_id)')and not exists(select 1 from pg_constraint where conindid=to_regclass('public.profiles_one_per_user_key')),'sole-profile fallback anatomy'),
  ('same_account_denial_policy',(select count(*)=1 from policies where table_name='conversations' and polname='Unbanned buyers create conversations' and check_expr like '%buyer_profile_id=(selectcurrent_active_profile_id()%' and check_expr like '%notcurrent_user_owns_profile(seller_profile_id)%'),'database-policy denial uses hidden boolean ownership helper; no owner output'),
  ('conversation_read_active_and_hide_isolated',(select count(*)=1 from policies where polname='participants view visible conversations' and using_expr like '%buyer_profile_id=(selectcurrent_active_profile_id()%' and using_expr like '%seller_profile_id=(selectcurrent_active_profile_id()%' and using_expr like '%s.profile_id=(selectcurrent_active_profile_id()%'),'active equality controls participant and only active hide state'),
  ('message_insert_active_two_present',(select count(*)=1 from policies where polname='Unbanned participants send messages' and check_expr like '%sender_profile_id=(selectcurrent_active_profile_id()%' and check_expr like '%buyer_profile_idisnotnull%' and check_expr like '%seller_profile_idisnotnull%' and check_expr like '%buyer_profile_id<>c.seller_profile_id%'),'active sender and two-present parent'),
  ('same_account_message_denial',(select count(*)=1 from policies where polname='Unbanned participants send messages' and check_expr like '%notcurrent_user_owns_profile(casewhen%'),'message policy also denies a sibling counterpart before a message row exists'),
  ('message_and_state_reads_active',(select count(*)=2 from policies where polname in('participants view messages','Participants read own conversation state') and using_expr like '%current_active_profile_id%'),'active exact read authority'),
  ('no_first_owned_match_remaining',not exists(select 1 from policies where (using_expr||check_expr) like '%current_user_owns_profile%' and polname not in('Unbanned buyers create conversations','Unbanned participants send messages')),'ownership helper remains only for neutral same-account target denial; actor identity is always active equality'),
  ('post_e_foundation_unchanged',(select count(*)=3 from pg_attribute where attrelid in('public.conversations'::regclass,'public.messages'::regclass) and attname in('buyer_profile_id','seller_profile_id','sender_profile_id') and not attnotnull) and (select count(*)=4 from pg_trigger where not tgisinternal and (tgrelid,tgname) in(('public.conversations'::regclass,'conversations_guard_participants'),('public.conversations'::regclass,'conversations_guard_unread'),('public.messages'::regclass,'messages_guard_active_participant'),('public.conversation_participant_state'::regclass,'conversation_participant_state_guard'))),'POST-E nullable/guard state'),
  ('rls_owner_force_unchanged',(select count(*)=3 and bool_and(c.relowner='postgres'::regrole and c.relrowsecurity and not c.relforcerowsecurity) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in('conversations','messages','conversation_participant_state')),'owner/RLS/FORCE'),
  ('five_rpcs_unchanged',(select count(*)=5 and count(*) filter(where (p.proname,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g')))) in(('append_unread_for','6023d0d555a24427a1d98f92d9d37e25'),('remove_unread_for','ca52e0ea7f804024cf6f9f7955dc9a62'),('hide_conversation','4e5756391924dc30ca09f7b535d36afa'),('unhide_conversation','7e7d2ce7d7cef459c1dd9a72a2eb87ab'),('find_and_unhide_conversation','ad6475d6ac60d2fe451597dbe78c2453')))=5 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation')),'MP4-G RPC scope unchanged'),
  ('realtime_replica_identity_unchanged',(select count(*)=3 and bool_and(c.relreplident='d') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in('conversations','messages','conversation_participant_state')) and (select count(*)=3 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename in('conversations','messages','conversation_participant_state')),'publication/replica identity'),
  ('package_d_privacy_intact',not has_column_privilege('anon','public.profiles','user_id','SELECT') and not has_column_privilege('authenticated','public.profiles','user_id','SELECT'),'owner linkage hidden')
 ) select string_agg(name||': '||detail,E'\n' order by name collate "C") into failures from checks where not ok;
 if failures is not null then raise exception 'MP4-F VERIFY STOP:%',E'\n'||failures using errcode='55000'; end if;
end$assert$;

with p as(select c.relname,p.polname,p.polcmd::text cmd,p.polpermissive,
 lower(regexp_replace(regexp_replace(coalesce(pg_get_expr(p.polqual,p.polrelid,false),''),'public\.','','g'),'[[:space:]]+','','g')) q,
 lower(regexp_replace(regexp_replace(coalesce(pg_get_expr(p.polwithcheck,p.polrelid,false),''),'public\.','','g'),'[[:space:]]+','','g')) w
 from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in('conversations','messages','conversation_participant_state'))
-- The report count is mechanically derived from the named assertion list above.
,check_names(name) as(values('owner_complete_context'),('five_target_policies_exact'),('authorization_helpers_exact'),('sole_profile_fallback_index_exact'),('same_account_denial_policy'),('conversation_read_active_and_hide_isolated'),('message_insert_active_two_present'),('same_account_message_denial'),('message_and_state_reads_active'),('no_first_owned_match_remaining'),('post_e_foundation_unchanged'),('rls_owner_force_unchanged'),('five_rpcs_unchanged'),('realtime_replica_identity_unchanged'),('package_d_privacy_intact'))
select 'SLICE_MP4_F_VERIFY' package,'GO' verdict,(select count(*)::int from check_names) passed,(select count(*)::int from check_names) total,'{}'::text[] findings,
 md5(string_agg(relname||'|'||polname||'|'||cmd||'|'||polpermissive||'|'||q||'|'||w,E'\n' order by relname collate "C",polname collate "C")) plain_policy_md5,
 'SESSION_COVERAGE=UNPROVEN: missing/invalid session_id silently empties messaging reads. Hosted Realtime remains owner-gated: prove active-only events, sibling silence, hidden-conversation silence, and subscription replacement on switch. mp4-policy-conversion-verify.sql intentionally STOPs post-F. Active-authority policy count=23 (13+5+5).'::text realtime_boundary
from p;
rollback;
