-- psy.market Slice MP-4-G PREFLIGHT — owner-run, read-only, no DML/DDL.
-- Every LIVE_PIN and emitted row/digest must be recomputed by the wingman from live.
-- DECLARED BOUNDARIES: SESSION_COVERAGE=UNPROVEN; hosted Realtime remains owner-gated;
-- mp4-policy-conversion-verify.sql intentionally STOPs after F; browser TRUNCATE cleanup is separate.
begin transaction isolation level repeatable read read only;
set local row_security=off;set local lock_timeout='5s';set local statement_timeout='30s';
lock table public.profiles,public.listings,public.conversations,public.messages,public.conversation_participant_state in share mode;

select 'SOURCE_FUNCTION_ROW' record_type,p.proname,regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') args,
 p.proowner::regrole::text owner,l.lanname,p.provolatile::text volatility,p.prosecdef,p.proisstrict,p.proleakproof,p.proparallel::text parallel,p.pronargdefaults,
 coalesce((select string_agg(case when cfg in('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by cfg collate "C") from unnest(coalesce(p.proconfig,array[]::text[])) cfg),'<none>') settings,
 regexp_replace(pg_get_function_result(p.oid),'public\.','','g') result,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g'))) body_hash
from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname in
 ('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation','unhide_conversation_for_message_recipient','update_conversation_last_message')
order by p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C";
select 'SOURCE_FUNCTION_ACL_ROW' record_type,p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||')' object_name,
 a.grantor::regrole::text grantor,case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable
from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a
where n.nspname='public' and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation','unhide_conversation_for_message_recipient','update_conversation_last_message')
order by (p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||')') collate "C",(a.grantor::regrole::text) collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C";
select 'TRIGGER_ROW' record_type,c.relname,p.tgname,f.proname,p.tgenabled::text enabled,
 lower(regexp_replace(regexp_replace(pg_get_triggerdef(p.oid,false),'public\.','','g'),'[[:space:]]+',' ','g')) definition
from pg_trigger p join pg_class c on c.oid=p.tgrelid join pg_proc f on f.oid=p.tgfoid where not p.tgisinternal and p.tgrelid='public.messages'::regclass order by p.tgname collate "C";
select 'INDEX_ROW' record_type,c.relname table_name,i.relname index_name,pg_get_indexdef(x.indexrelid) definition
from pg_index x join pg_class c on c.oid=x.indrelid join pg_class i on i.oid=x.indexrelid where x.indrelid in('public.conversations'::regclass,'public.messages'::regclass,'public.conversation_participant_state'::regclass) order by c.relname collate "C",i.relname collate "C";

with
f as(select p.proname,regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') args,p.proowner::regrole::text owner,l.lanname,p.provolatile::text volatility,p.prosecdef,p.proisstrict,p.proleakproof,p.proparallel::text parallel,p.pronargdefaults,
 coalesce((select string_agg(case when cfg in('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by cfg collate "C") from unnest(coalesce(p.proconfig,array[]::text[]))cfg),'<none>')settings,regexp_replace(pg_get_function_result(p.oid),'public\.','','g')result,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g')))body_hash
 from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation','unhide_conversation_for_message_recipient','update_conversation_last_message')),
expected_f(proname,args,owner,lanname,volatility,prosecdef,proisstrict,proleakproof,parallel,pronargdefaults,settings,result,body_hash)as(values
 ('append_unread_for','conv_id uuid, profile_id text','postgres','plpgsql','v',true,false,false,'u',0,'search_path=pg_catalog, public, auth','void','6023d0d555a24427a1d98f92d9d37e25'),
 ('find_and_unhide_conversation','target_other_profile_id uuid, target_listing_id uuid','postgres','plpgsql','v',true,false,false,'u',1,'search_path=pg_catalog, public, auth','uuid','ad6475d6ac60d2fe451597dbe78c2453'),
 ('hide_conversation','target_conversation_id uuid','postgres','plpgsql','v',true,false,false,'u',0,'search_path=pg_catalog, public, auth','void','4e5756391924dc30ca09f7b535d36afa'),
 ('remove_unread_for','conv_id uuid, profile_id text','postgres','plpgsql','v',true,false,false,'u',0,'search_path=pg_catalog, public, auth','void','ca52e0ea7f804024cf6f9f7955dc9a62'),
 ('unhide_conversation','target_conversation_id uuid','postgres','plpgsql','v',true,false,false,'u',0,'search_path=pg_catalog, public, auth','void','7e7d2ce7d7cef459c1dd9a72a2eb87ab'),
 ('unhide_conversation_for_message_recipient','','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','trigger','65000503f5c585632d5cae3282217b43'),
 ('update_conversation_last_message','','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','trigger','396ba90811a1f9ba79cbdf3bc3f5b060')),
fa as(select p.proname,a.grantor::regrole::text grantor,case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a where n.nspname='public' and p.proname in(select proname from expected_f)),
expected_fa(proname,grantor,grantee,privilege_type,is_grantable)as(
 select name,'postgres',r,'EXECUTE',false from unnest(array['append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation'])name cross join unnest(array['authenticated','postgres','service_role'])r
 union all select name,'postgres',r,'EXECUTE',false from unnest(array['unhide_conversation_for_message_recipient','update_conversation_last_message'])name cross join unnest(array['postgres','service_role'])r),
ta as(select c.relname table_name,a.grantor::regrole::text grantor,case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner)))a where n.nspname='public' and c.relname in('conversations','messages','conversation_participant_state')),
legal(p)as(select unnest(case when current_setting('server_version_num')::int>=170000 then array['DELETE','INSERT','MAINTAIN','REFERENCES','SELECT','TRIGGER','TRUNCATE','UPDATE'] else array['DELETE','INSERT','REFERENCES','SELECT','TRIGGER','TRUNCATE','UPDATE'] end)),
expected_ta(table_name,grantor,grantee,privilege_type,is_grantable)as(
 select t,'postgres',r,p,false from unnest(array['conversation_participant_state','conversations','messages'])t cross join unnest(array['postgres','service_role'])r cross join legal
 union all select 'conversations','postgres',r,p,false from unnest(array['anon','authenticated'])r cross join legal where p<>'DELETE'
 union all select 'messages','postgres',r,p,false from unnest(array['anon','authenticated'])r cross join legal
 union all select 'conversation_participant_state','postgres','authenticated','SELECT',false
 union all select t,'postgres','audit_readonly','SELECT',false from unnest(array['conversations','messages'])t),
checks(name,ok,detail)as(values
 ('owner_complete_context',current_user='postgres' and session_user='postgres' and(select rolsuper or rolbypassrls from pg_roles where rolname=current_user),'LIVE_PIN owner/BYPASSRLS completeness'),
 ('seven_source_functions_exact',not exists((select * from f except select * from expected_f)union all(select * from expected_f except select * from f)),'LIVE_PIN complete overload/attribute/settings/result/body manifest'),
 ('seven_source_function_acls_exact',not exists((select * from fa except select * from expected_fa)union all(select * from expected_fa except select * from fa)),'LIVE_PIN exploded ACL sets preserve authenticated/service-role intent'),
 ('post_f_policy_family_exact',(select count(*)=5 and count(*) filter(where (coalesce(pg_get_expr(polqual,polrelid,false),'')||coalesce(pg_get_expr(polwithcheck,polrelid,false),''))like'%current_active_profile_id%')=5 from pg_policy where polrelid in('public.conversations'::regclass,'public.messages'::regclass,'public.conversation_participant_state'::regclass)),'LIVE_PIN exact post-F five-policy active family; emitted F policy manifest recompute required'),
 ('post_e_nullable_guards_exact',(select count(*)=3 from pg_attribute where attrelid in('public.conversations'::regclass,'public.messages'::regclass)and attname in('buyer_profile_id','seller_profile_id','sender_profile_id')and not attnotnull)and(select count(*)=4 from pg_trigger where not tgisinternal and(tgrelid,tgname)in(('public.conversations'::regclass,'conversations_guard_participants'),('public.conversations'::regclass,'conversations_guard_unread'),('public.messages'::regclass,'messages_guard_active_participant'),('public.conversation_participant_state'::regclass,'conversation_participant_state_guard'))),'LIVE_PIN nullable columns/four structural guards'),
 ('trigger_bindings_exact',(select count(*)=2 from pg_trigger where not tgisinternal and(tgrelid,tgname,tgfoid)in(('public.messages'::regclass,'messages_unhide_recipient_conversation',to_regprocedure('public.unhide_conversation_for_message_recipient()')),('public.messages'::regclass,'on_message_insert',to_regprocedure('public.update_conversation_last_message()')))),'LIVE_PIN exact enabled AFTER INSERT row bindings; emitted rows'),
 ('participant_constraints_and_indexes_exact',(select count(*)=9 from pg_index where indrelid in('public.conversations'::regclass,'public.messages'::regclass,'public.conversation_participant_state'::regclass))and(select count(*)=5 from pg_constraint where conname in('conversations_buyer_seller_differ','unique_conversation','conversation_participant_state_pkey','conversation_participant_state_profile_id_fkey','conversation_participant_state_conversation_id_fkey')),'LIVE_PIN complete emitted index rows and concurrency uniqueness constraints'),
 ('table_acls_exact',not exists((select * from ta except select * from expected_ta)union all(select * from expected_ta except select * from ta)),'LIVE_PIN exact ACLs incl audit_readonly and PG17 MAINTAIN/TRUNCATE warts'),
 ('active_helpers_exact',(select count(*)=4 and count(*)filter(where(p.proname,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g'))))in(('current_active_profile_id','8ab19811ddcf117a757e7663efc5ac77'),('current_active_profile_id','6f6b53dbd223db8ba168073c196f7b1a'),('current_user_owns_profile','b18b8e4f01df72097d092352423ab8af'),('current_user_is_banned','682d0a1d82cd433e5bd7deb4aeee5ede')))=4 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where(n.nspname='private'and p.proname='current_active_profile_id')or(n.nspname='public'and p.proname in('current_active_profile_id','current_user_owns_profile','current_user_is_banned'))),'LIVE_PIN resolver/ownership/ban dependency bodies; full attributes/ACL rows recompute required'),
 ('sole_profile_fallback_exact',exists(select 1 from pg_index i where i.indexrelid=to_regclass('public.profiles_one_per_user_key')and i.indrelid='public.profiles'::regclass and i.indisunique and i.indisvalid and i.indisready and i.indpred is null and pg_get_indexdef(i.indexrelid)='CREATE UNIQUE INDEX profiles_one_per_user_key ON public.profiles USING btree (user_id)')and not exists(select 1 from pg_constraint where conindid=to_regclass('public.profiles_one_per_user_key')),'LIVE_PIN sole-profile current-behavior fallback'),
 ('realtime_replica_identity_exact',(select count(*)=3 and bool_and(relreplident='d')from pg_class where oid in('public.conversations'::regclass,'public.messages'::regclass,'public.conversation_participant_state'::regclass))and(select count(*)=3 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename in('conversations','messages','conversation_participant_state')),'LIVE_PIN publication/replica identity'),
 ('package_d_privacy_intact',not has_column_privilege('anon','public.profiles','user_id','SELECT')and not has_column_privilege('authenticated','public.profiles','user_id','SELECT'),'LIVE_PIN owner linkage hidden')),
summary as(select bool_and(ok)all_ok,count(*)filter(where ok)::int passed,count(*)::int total,coalesce(array_agg(name||': '||detail order by name collate "C")filter(where not ok),'{}'::text[])findings from checks)
select 'SLICE_MP4_G_PREFLIGHT' package,case when all_ok then'GO'else'STOP'end verdict,passed,total,findings,
 (select md5(string_agg(proname||'|'||args||'|'||owner||'|'||lanname||'|'||volatility||'|'||prosecdef||'|'||proisstrict||'|'||proleakproof||'|'||parallel||'|'||pronargdefaults||'|'||settings||'|'||result||'|'||body_hash,E'\n' order by proname collate "C",args collate "C"))from f)normalized_function_md5,
 (select md5(string_agg(proname||'|'||grantor||'|'||grantee||'|'||privilege_type||'|'||is_grantable,E'\n' order by proname collate "C",grantor collate "C",grantee collate "C",privilege_type collate "C"))from fa)exploded_function_acl_md5,
 'LIVE_PIN recompute: seven full function rows and ACL rows; two trigger rows; complete index rows; post-F policy digest; post-E constraints/guards; table ACLs incl audit_readonly/PG17 MAINTAIN/TRUNCATE; active/ownership/ban helper definitions+ACLs; sole-profile index; publication/replica identity; Package-D privacy.'::text wingman_recompute,
 'SESSION_COVERAGE=UNPROVEN; hosted Realtime owner gate; historical mp4-policy-conversion-verify STOP; TRUNCATE remediation separate; deletion/SET NULL cutover remains held.'::text boundary from summary;
rollback;
