#!/usr/bin/env bash
set -euo pipefail
# Self-contained disposable lifecycle. Creates and drops only a fresh local DB.
HOST=${MP4E_HOST:-/tmp/mp4c2-sock}; PORT=${MP4E_PORT:-55442}; USER=${MP4E_USER:-postgres}; ADMIN=${MP4E_ADMIN_USER:-supabase_admin}
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd); DB=${MP4E_DB:-mp4e_disposable_$$}; LOG_DIR=${MP4E_LOG_DIR:-$(mktemp -d)}; mkdir -p "$LOG_DIR"
P=(psql -X -q -v ON_ERROR_STOP=1 -h "$HOST" -p "$PORT" -U "$USER" -d "$DB")
FILES=("$ROOT/supabase/chunks/slice-mp4-e-preflight.sql" "$ROOT/supabase/chunks/slice-mp4-e-apply.sql" "$ROOT/supabase/chunks/slice-mp4-e-verify.sql" "$ROOT/supabase/chunks/slice-mp4-e-rollback.sql" "$ROOT/supabase/chunks/slice-mp4-e-disposable-runtime.sql" "$ROOT/supabase/chunks/slice-mp4-e-disposable-harness.sh")
cleanup(){ dropdb -h "$HOST" -p "$PORT" -U "$ADMIN" --if-exists "$DB" >/dev/null 2>&1 || true; }; trap cleanup EXIT
sha256sum "${FILES[@]}" >"$LOG_DIR/start.sha256"; cleanup; createdb -h "$HOST" -p "$PORT" -U "$ADMIN" -T template0 -O "$USER" "$DB"
"${P[@]}" >"$LOG_DIR/setup.log" <<'SQL'
create schema auth; create schema private;
create extension if not exists pgcrypto;
create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
create function auth.uid() returns uuid language sql stable as $$select nullif(auth.jwt()->>'sub','')::uuid$$;
create table public.profiles(id uuid primary key,user_id uuid not null,handle text not null unique,unique(id,user_id));
create table public.listings(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id));
create table public.conversations(id uuid primary key default gen_random_uuid(),listing_id uuid references public.listings(id) on delete set null,buyer_profile_id uuid not null,seller_profile_id uuid not null,last_message_at timestamptz not null default now(),last_message_body text,created_at timestamptz not null default now(),unread_for text[] default '{}'::text[],constraint conversations_buyer_profile_id_fkey foreign key(buyer_profile_id) references public.profiles(id) on delete cascade,constraint conversations_seller_profile_id_fkey foreign key(seller_profile_id) references public.profiles(id) on delete cascade,constraint unique_conversation unique(listing_id,buyer_profile_id,seller_profile_id),constraint conversations_buyer_seller_differ check(buyer_profile_id<>seller_profile_id));
create index idx_conversations_buyer on public.conversations(buyer_profile_id); create index idx_conversations_seller on public.conversations(seller_profile_id); create index idx_conversations_last_message on public.conversations(last_message_at desc);
create table public.messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null,sender_profile_id uuid not null,body text not null,created_at timestamptz not null default now(),constraint messages_conversation_id_fkey foreign key(conversation_id) references public.conversations(id) on delete cascade,constraint messages_sender_profile_id_fkey foreign key(sender_profile_id) references public.profiles(id) on delete cascade);
create index idx_messages_conversation on public.messages(conversation_id,created_at);
create table public.conversation_participant_state(conversation_id uuid not null,profile_id uuid not null,hidden_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint conversation_participant_state_pkey primary key(conversation_id,profile_id),constraint conversation_participant_state_conversation_id_fkey foreign key(conversation_id) references public.conversations(id) on delete cascade,constraint conversation_participant_state_profile_id_fkey foreign key(profile_id) references public.profiles(id) on delete cascade);
create index conversation_participant_state_hidden_profile_idx on public.conversation_participant_state(profile_id,conversation_id) where hidden_at is not null;
create table private.account_session_active_profiles(session_id uuid primary key,user_id uuid not null,profile_id uuid not null,constraint account_session_active_profiles_profile_owner_fkey foreign key(profile_id,user_id) references public.profiles(id,user_id) on delete cascade);
create function private.current_active_profile_id() returns uuid language sql stable security definer set search_path='' as $$select s.profile_id from private.account_session_active_profiles s where s.session_id=nullif(auth.jwt()->>'session_id','')::uuid and s.user_id=auth.uid()$$;
create function public.current_active_profile_id() returns uuid language sql stable security definer set search_path='' as $$select private.current_active_profile_id()$$;
create function public.current_user_is_active_profile(target uuid) returns boolean language sql stable security definer set search_path='' as $$select target is not null and target=private.current_active_profile_id()$$;
create function public.enforce_conversation_listing_seller() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$declare expected_seller_profile_id uuid;begin if new.listing_id is null then return new;end if;select l.profile_id into expected_seller_profile_id from public.listings l where l.id=new.listing_id;if expected_seller_profile_id is null then raise exception 'Listing does not exist';end if;if new.seller_profile_id<>expected_seller_profile_id then raise exception 'Conversation seller must own the linked listing';end if;return new;end$$;
create function public.unhide_conversation_for_message_recipient() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$begin update public.conversation_participant_state s set hidden_at=null,updated_at=now() from public.conversations c where c.id=new.conversation_id and s.conversation_id=c.id and s.hidden_at is not null and s.profile_id=case when new.sender_profile_id=c.buyer_profile_id then c.seller_profile_id when new.sender_profile_id=c.seller_profile_id then c.buyer_profile_id else null end;return new;end$$;
create function public.update_conversation_last_message() returns trigger language plpgsql volatile security definer set search_path='' as $$declare affected_rows bigint;begin if tg_when<>'AFTER' or tg_level<>'ROW' or tg_op<>'INSERT' or tg_table_schema<>'public' or tg_table_name<>'messages' then raise exception 'Unexpected update_conversation_last_message trigger context' using errcode='42501';end if;update public.conversations c set last_message_at=new.created_at,last_message_body=pg_catalog.left(new.body,120) where c.id=new.conversation_id;get diagnostics affected_rows=row_count;if affected_rows<>1 then raise exception 'Message parent conversation does not exist' using errcode='23503';end if;return new;end$$;
create trigger conversations_enforce_listing_seller before insert or update of listing_id,seller_profile_id on public.conversations for each row execute function public.enforce_conversation_listing_seller();
create trigger messages_unhide_recipient_conversation after insert on public.messages for each row execute function public.unhide_conversation_for_message_recipient();
create trigger on_message_insert after insert on public.messages for each row execute function public.update_conversation_last_message();
revoke all on function private.current_active_profile_id(),public.current_active_profile_id(),public.current_user_is_active_profile(uuid),public.enforce_conversation_listing_seller(),public.unhide_conversation_for_message_recipient(),public.update_conversation_last_message() from public;
grant execute on function public.current_active_profile_id(),public.current_user_is_active_profile(uuid) to authenticated;
grant execute on function public.enforce_conversation_listing_seller(),public.unhide_conversation_for_message_recipient(),public.update_conversation_last_message() to service_role;
grant usage on schema public to anon,authenticated,service_role; grant select,insert,update on public.conversations,public.messages,public.conversation_participant_state to authenticated; grant select,insert,update,delete on all tables in schema public to service_role;
alter table public.conversations enable row level security; alter table public.messages enable row level security; alter table public.conversation_participant_state enable row level security;
create policy "Unbanned buyers create conversations" on public.conversations for insert to authenticated with check(true);
create policy "participants view visible conversations" on public.conversations for select to authenticated using(true);
create policy "Unbanned participants send messages" on public.messages for insert to authenticated with check(true);
create policy "participants view messages" on public.messages for select to authenticated using(true);
create policy "Participants read own conversation state" on public.conversation_participant_state for select to authenticated using(true);
create publication supabase_realtime for table public.conversations,public.messages,public.conversation_participant_state;
SQL
verdict(){ local f=$1 label=$2 hostile=${3:-no}; local out="$LOG_DIR/$label.log"; if [[ $hostile == yes ]];then "${P[@]}" -At -c 'set search_path=pg_catalog' -f "$f" >"$out";else "${P[@]}" -At -f "$f" >"$out";fi; grep -q '|GO|' "$out"; printf '%s=GO\n' "$label"; }
state(){ "${P[@]}" -At -c "select md5(string_agg(x,'|' order by x collate \"C\")) from (select p.proname||':'||p.ctid::text x from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('enforce_conversation_listing_seller','unhide_conversation_for_message_recipient','update_conversation_last_message','guard_conversation_participants','guard_conversation_unread_participants','guard_message_active_participant','guard_conversation_participant_state') union all select c.relname||':'||a.attname||':'||a.attnotnull from pg_attribute a join pg_class c on c.oid=a.attrelid where a.attrelid in('public.conversations'::regclass,'public.messages'::regclass) and a.attname in('buyer_profile_id','seller_profile_id','sender_profile_id'))s;"; }
version=$("${P[@]}" -At -c "show server_version_num"); if ((version>=170000));then echo POSTGRESQL_17_SEMANTICS=PASS;else echo "POSTGRESQL_17_SEMANTICS=UNAVAILABLE(server_version_num=$version); PostgreSQL 16 lifecycle is supporting evidence only";fi
verdict "$ROOT/supabase/chunks/slice-mp4-e-preflight.sql" preflight-default; verdict "$ROOT/supabase/chunks/slice-mp4-e-preflight.sql" preflight-hostile yes
"${P[@]}" -f "$ROOT/supabase/chunks/slice-mp4-e-apply.sql" >"$LOG_DIR/apply.log"; before=$(state); "${P[@]}" -f "$ROOT/supabase/chunks/slice-mp4-e-apply.sql" >"$LOG_DIR/apply-noop.log"; [[ $before == "$(state)" ]]; echo APPLY_NOOP=PASS
verdict "$ROOT/supabase/chunks/slice-mp4-e-verify.sql" verify-default; verdict "$ROOT/supabase/chunks/slice-mp4-e-verify.sql" verify-hostile yes
"${P[@]}" -f "$ROOT/supabase/chunks/slice-mp4-e-disposable-runtime.sql" >"$LOG_DIR/runtime.log" 2>&1; grep -q MP4E_FUTURE_SHAPE_MATRIX=PASS "$LOG_DIR/runtime.log"; echo FUTURE_SHAPE_MATRIX=PASS
"${P[@]}" -f "$ROOT/supabase/chunks/slice-mp4-e-rollback.sql" >"$LOG_DIR/rollback.log"; before=$(state); "${P[@]}" -f "$ROOT/supabase/chunks/slice-mp4-e-rollback.sql" >"$LOG_DIR/rollback-noop.log"; [[ $before == "$(state)" ]]; echo ROLLBACK_NOOP=PASS
verdict "$ROOT/supabase/chunks/slice-mp4-e-preflight.sql" restored-default; verdict "$ROOT/supabase/chunks/slice-mp4-e-preflight.sql" restored-hostile yes
"${P[@]}" -f "$ROOT/supabase/chunks/slice-mp4-e-apply.sql" >"$LOG_DIR/second-apply.log"; verdict "$ROOT/supabase/chunks/slice-mp4-e-verify.sql" second-verify; "${P[@]}" -f "$ROOT/supabase/chunks/slice-mp4-e-rollback.sql" >"$LOG_DIR/final-rollback.log"; verdict "$ROOT/supabase/chunks/slice-mp4-e-preflight.sql" final-restored
sha256sum "${FILES[@]}" >"$LOG_DIR/end.sha256"; cmp "$LOG_DIR/start.sha256" "$LOG_DIR/end.sha256"; echo "SLICE_MP4_E_BOUND_LIFECYCLE=PASS logs=$LOG_DIR"
