-- psy.market Slice MP-4-G VERIFY — owner-run read-only exact target proof.
-- Every LIVE_PIN/digest is wingman-recomputed. No runtime call is made here.
-- DECLARED INVALIDATIONS: slice-mp4-e-verify.sql, slice-mp4-f-verify.sql, and
-- slice-mp4-f-preflight.sql intentionally STOP after G because they pin pre-G bodies.
begin transaction isolation level repeatable read read only;
set local row_security=off;set local lock_timeout='5s';set local statement_timeout='30s';
lock table public.profiles,public.listings,public.conversations,public.messages,public.conversation_participant_state in share mode;

select 'TARGET_FUNCTION_ROW' record_type,p.proname,regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')args,p.proowner::regrole::text owner,l.lanname,p.provolatile::text volatility,p.prosecdef,p.proisstrict,p.proleakproof,p.proparallel::text parallel,p.pronargdefaults,
 coalesce((select string_agg(case when cfg in('search_path=','search_path=""')then'search_path=<empty>'else cfg end,','order by cfg collate "C")from unnest(coalesce(p.proconfig,array[]::text[]))cfg),'<none>')settings,regexp_replace(pg_get_function_result(p.oid),'public\.','','g')result,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g')))body_hash
from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public'and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation','unhide_conversation_for_message_recipient','update_conversation_last_message')order by p.proname collate "C";
select 'TARGET_FUNCTION_ACL_ROW' record_type,p.proname,a.grantor::regrole::text grantor,case when a.grantee=0 then'PUBLIC'else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a where n.nspname='public'and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation','unhide_conversation_for_message_recipient','update_conversation_last_message')order by p.proname collate "C",(a.grantor::regrole::text) collate "C",(case when a.grantee=0 then'PUBLIC'else a.grantee::regrole::text end) collate "C";

do $assert$
declare failures text;
begin
with f as(select p.proname,regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')args,p.proowner::regrole::text owner,l.lanname,p.provolatile::text volatility,p.prosecdef,p.proisstrict,p.proleakproof,p.proparallel::text parallel,p.pronargdefaults,coalesce((select string_agg(case when cfg in('search_path=','search_path=""')then'search_path=<empty>'else cfg end,','order by cfg collate "C")from unnest(coalesce(p.proconfig,array[]::text[]))cfg),'<none>')settings,regexp_replace(pg_get_function_result(p.oid),'public\.','','g')result,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g')))body_hash from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public'and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation','unhide_conversation_for_message_recipient','update_conversation_last_message')),
e(proname,args,owner,lanname,volatility,prosecdef,proisstrict,proleakproof,parallel,pronargdefaults,settings,result,body_hash)as(values
 ('append_unread_for','conv_id uuid, profile_id text','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','void','d11f82a4b1d43fe42bbe3a6423660000'),
 ('find_and_unhide_conversation','target_other_profile_id uuid, target_listing_id uuid','postgres','plpgsql','v',true,false,false,'u',1,'search_path=<empty>','uuid','a54c515118342fae1db226b8dc09c8c8'),
 ('hide_conversation','target_conversation_id uuid','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','void','be76125d658a1ad3077fbc2d8b8e9c75'),
 ('remove_unread_for','conv_id uuid, profile_id text','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','void','77188697a16d747abfb12eaf16d5a1a6'),
 ('unhide_conversation','target_conversation_id uuid','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','void','5ef5fa1296aed8f13fb52ab5cf5fdc99'),
 ('unhide_conversation_for_message_recipient','','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','trigger','32ed416178cb477bfdb363eef779f10f'),
 ('update_conversation_last_message','','postgres','plpgsql','v',true,false,false,'u',0,'search_path=<empty>','trigger','5a285350e95fb623199956f4d43b7953')),
fa as(select p.proname,a.grantor::regrole::text grantor,case when a.grantee=0 then'PUBLIC'else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a where n.nspname='public'and p.proname in(select proname from e)),
ea(proname,grantor,grantee,privilege_type,is_grantable)as(select name,'postgres',r,'EXECUTE',false from unnest(array['append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation'])name cross join unnest(array['authenticated','postgres','service_role'])r union all select name,'postgres',r,'EXECUTE',false from unnest(array['unhide_conversation_for_message_recipient','update_conversation_last_message'])name cross join unnest(array['postgres','service_role'])r),
helper_state as(select n.nspname,p.proname,regexp_replace(pg_get_function_identity_arguments(p.oid),'(public|private)\.','','g')args,p.proowner::regrole::text owner,l.lanname,p.provolatile::text volatility,p.prosecdef,p.proisstrict,p.proleakproof,p.proparallel::text parallel,p.pronargdefaults,coalesce((select string_agg(case when cfg in('search_path=','search_path=""')then'search_path=<empty>'else cfg end,','order by cfg collate "C")from unnest(coalesce(p.proconfig,array[]::text[]))cfg),'<none>')settings,regexp_replace(pg_get_function_result(p.oid),'(public|private)\.','','g')result,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g')))body_hash from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where(n.nspname='private'and p.proname='current_active_profile_id')or(n.nspname='public'and p.proname in('current_active_profile_id','current_user_owns_profile','current_user_is_banned'))),
expected_helper_state(nspname,proname,args,owner,lanname,volatility,prosecdef,proisstrict,proleakproof,parallel,pronargdefaults,settings,result,body_hash)as(values('private','current_active_profile_id','','postgres','plpgsql','s',true,false,false,'u',0,'search_path=<empty>','uuid','8ab19811ddcf117a757e7663efc5ac77'),('public','current_active_profile_id','','postgres','sql','s',true,false,false,'u',0,'search_path=<empty>','uuid','6f6b53dbd223db8ba168073c196f7b1a'),('public','current_user_owns_profile','target_profile_id uuid','postgres','sql','s',true,false,false,'u',0,'search_path=<empty>','boolean','b18b8e4f01df72097d092352423ab8af'),('public','current_user_is_banned','','postgres','sql','s',true,false,false,'u',0,'search_path=pg_catalog, public, auth','boolean','682d0a1d82cd433e5bd7deb4aeee5ede')),
helper_acl as(select n.nspname||'.'||p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'(public|private)\.','','g')||')'object_name,a.grantor::regrole::text grantor,case when a.grantee=0 then'PUBLIC'else a.grantee::regrole::text end grantee,a.privilege_type,a.is_grantable from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a where(n.nspname='private'and p.proname='current_active_profile_id')or(n.nspname='public'and p.proname in('current_active_profile_id','current_user_owns_profile','current_user_is_banned'))),
expected_helper_acl(object_name,grantor,grantee,privilege_type,is_grantable)as(values('private.current_active_profile_id()','postgres','postgres','EXECUTE',false),('public.current_active_profile_id()','postgres','authenticated','EXECUTE',false),('public.current_active_profile_id()','postgres','postgres','EXECUTE',false),('public.current_user_owns_profile(target_profile_id uuid)','postgres','authenticated','EXECUTE',false),('public.current_user_owns_profile(target_profile_id uuid)','postgres','postgres','EXECUTE',false),('public.current_user_is_banned()','postgres','authenticated','EXECUTE',false),('public.current_user_is_banned()','postgres','postgres','EXECUTE',false),('public.current_user_is_banned()','postgres','service_role','EXECUTE',false)),
checks(name,ok,detail)as(values
 ('owner_complete_context',current_user='postgres'and session_user='postgres'and(select rolsuper or rolbypassrls from pg_roles where rolname=current_user),'owner/BYPASSRLS'),
 ('seven_target_functions_exact',not exists((select * from f except select * from e)union all(select * from e except select * from f)),'complete attributes/settings/results/body hashes'),
 ('seven_target_acls_exact',not exists((select * from fa except select * from ea)union all(select * from ea except select * from fa)),'exact authenticated/service-role ACL intent'),
 ('authorization_helpers_exact',not exists((select * from helper_state except select * from expected_helper_state)union all(select * from expected_helper_state except select * from helper_state))and not exists((select * from helper_acl except select * from expected_helper_acl)union all(select * from expected_helper_acl except select * from helper_acl)),'full active/ownership/ban helper attributes/bodies/settings/results/direct ACLs'),
 ('five_rpcs_active_exact',(select count(*)=5 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation')and p.prosrc like'%current_active_profile_id%'),'no any-owned actor selection'),
 ('no_first_branch_wins',(select count(*)=4 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation')and p.prosrc like'%Both conversation participants belong to the caller account%'),'explicit dual-owned failure'),
 ('find_contact_guards_exact',(select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='find_and_unhide_conversation'and p.prosrc like'%target_other_profile_id=active_profile_id%'and p.prosrc like'%current_user_owns_profile(target_other_profile_id)%'and p.prosrc like'%buyer_profile_id is not null%'and p.prosrc like'%for update%'),'active exact/neutral same-account/deleted-safe lookup'),
 ('unread_lock_and_target_guards',(select count(*)=2 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname in('append_unread_for','remove_unread_for')and p.prosrc like'%for update%')and(select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='append_unread_for'and p.prosrc like'%One-sided retained conversations are read-only%')and(select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='remove_unread_for'and p.prosrc not like'%One-sided retained conversations are read-only%'),'append remains retained read-only; survivor can clear own unread; both lock exact target'),
 ('hide_survivor_state_exact',(select count(*)=2 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname in('hide_conversation','unhide_conversation')and p.prosrc like'%active_profile_id%'and p.prosrc like'%on conflict%'),'only active/surviving participant state'),
 ('recipient_unhide_exact',(select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='unhide_conversation_for_message_recipient'and p.prosrc like'%Recipient-unhide requires two present participants%'and p.prosrc like'%profile_id=recipient_profile_id%'and p.prosrc not like'%insert into%'),'recipient only; no state recreation'),
 ('parent_summary_exact',(select count(*)=1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname='update_conversation_last_message'and p.prosrc like'%for update%'and p.prosrc like'%One-sided retained conversations are read-only%'and p.prosrc like'%Message sender is not a conversation participant%'),'exact parent/sender/null guards'),
 ('trigger_bindings_unchanged',(select count(*)=2 from pg_trigger where not tgisinternal and(tgrelid,tgname,tgfoid)in(('public.messages'::regclass,'messages_unhide_recipient_conversation',to_regprocedure('public.unhide_conversation_for_message_recipient()')),('public.messages'::regclass,'on_message_insert',to_regprocedure('public.update_conversation_last_message()')))),'exact existing bindings'),
 ('trigger_functions_not_client_callable',not has_function_privilege('anon','public.unhide_conversation_for_message_recipient()','EXECUTE')and not has_function_privilege('authenticated','public.unhide_conversation_for_message_recipient()','EXECUTE')and not has_function_privilege('anon','public.update_conversation_last_message()','EXECUTE')and not has_function_privilege('authenticated','public.update_conversation_last_message()','EXECUTE'),'direct invocation denied'),
 ('post_f_policies_unchanged',(select count(*)=5 and count(*)filter(where(coalesce(pg_get_expr(polqual,polrelid,false),'')||coalesce(pg_get_expr(polwithcheck,polrelid,false),''))like'%current_active_profile_id%')=5 from pg_policy where polrelid in('public.conversations'::regclass,'public.messages'::regclass,'public.conversation_participant_state'::regclass)),'five active messaging policies'),
 ('active_authority_policy_total_exact',(select count(*)=23 from pg_policy p where(coalesce(pg_get_expr(p.polqual,p.polrelid,false),'')||coalesce(pg_get_expr(p.polwithcheck,p.polrelid,false),''))like'%current_active_profile_id%'),'exact post-F active-authority policy total=23'),
 ('post_e_foundation_unchanged',(select count(*)=3 from pg_attribute where attrelid in('public.conversations'::regclass,'public.messages'::regclass)and attname in('buyer_profile_id','seller_profile_id','sender_profile_id')and not attnotnull)and(select count(*)=4 from pg_trigger where not tgisinternal and(tgrelid,tgname)in(('public.conversations'::regclass,'conversations_guard_participants'),('public.conversations'::regclass,'conversations_guard_unread'),('public.messages'::regclass,'messages_guard_active_participant'),('public.conversation_participant_state'::regclass,'conversation_participant_state_guard'))),'nullable/guards unchanged'),
 ('realtime_privacy_unchanged',(select count(*)=3 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename in('conversations','messages','conversation_participant_state'))and not has_column_privilege('anon','public.profiles','user_id','SELECT')and not has_column_privilege('authenticated','public.profiles','user_id','SELECT'),'publication and Package-D privacy'))
select string_agg(name||': '||detail,E'\n'order by name collate "C")into failures from checks where not ok;
if failures is not null then raise exception 'MP4-G VERIFY STOP:%',E'\n'||failures using errcode='55000';end if;
end$assert$;
with f as(select p.proname,regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')args,md5(btrim(regexp_replace(replace(p.prosrc,E'\r\n',E'\n'),'[[:space:]]+',' ','g')))hash from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname in('append_unread_for','remove_unread_for','hide_conversation','unhide_conversation','find_and_unhide_conversation','unhide_conversation_for_message_recipient','update_conversation_last_message')),names(name)as(values('owner_complete_context'),('seven_target_functions_exact'),('seven_target_acls_exact'),('authorization_helpers_exact'),('five_rpcs_active_exact'),('no_first_branch_wins'),('find_contact_guards_exact'),('unread_lock_and_target_guards'),('hide_survivor_state_exact'),('recipient_unhide_exact'),('parent_summary_exact'),('trigger_bindings_unchanged'),('trigger_functions_not_client_callable'),('post_f_policies_unchanged'),('active_authority_policy_total_exact'),('post_e_foundation_unchanged'),('realtime_privacy_unchanged'))
select 'SLICE_MP4_G_VERIFY'package,'GO'verdict,(select count(*)::int from names)passed,(select count(*)::int from names)total,'{}'::text[]findings,md5(string_agg(proname||'|'||args||'|'||hash,E'\n'order by proname collate "C",args collate "C"))normalized_function_md5,'74646c18a5c069ee4af86d0bb19669b6'::text expected_normalized_function_md5,'SESSION_COVERAGE=UNPROVEN; hosted Realtime owner gate; mp4-policy-conversion-verify.sql, slice-mp4-e-verify.sql, slice-mp4-f-verify.sql, and slice-mp4-f-preflight.sql intentionally STOP post-G; TRUNCATE remediation separate; deletion/SET NULL cutover held.'::text boundary from f;
rollback;
