-- psy.market Wall highlights: posts highlight state, max-five fence, active-profile toggle RPC
-- Policy fingerprints use plain two-argument pg_get_expr(), matching the admitted MP4-D evidence.
-- Exact source pins: live-verified MP4-D after-state (2026-08-15). No live DDL/DML was run by the author.
-- ROLLBACK — OWNER-RUN IN SUPABASE SQL EDITOR.
-- Rollback removes all highlight state; it cannot preserve highlight choices made while active.
begin;
set local lock_timeout='5s';
set local statement_timeout='60s';
lock table public.posts in access exclusive mode;
do $transition$
declare source_ok boolean; target_ok boolean;
begin
 if current_user<>'postgres' or session_user<>'postgres' then raise exception 'Wall highlights ROLLBACK refused: owner SQL Editor context required' using errcode='42501'; end if;
 with
relation_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||c.relowner::regrole::text||'|'||c.relkind::text||'|'||c.relpersistence::text||'|'||case when c.relrowsecurity then 't' else 'f' end||'|'||case when c.relforcerowsecurity then 't' else 'f' end||'|'||c.relreplident::text,E'\n' order by c.relname collate "C"),'')) h
 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
column_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||a.attnum||'|'||a.attname||'|'||regexp_replace(format_type(a.atttypid,a.atttypmod),'public\.','','g')||'|'||case when a.attnotnull then 't' else 'f' end||'|'||regexp_replace(coalesce(pg_get_expr(d.adbin,d.adrelid,true),''),'public\.','','g')||'|'||case when a.attcollation=0 then '-' else regexp_replace(a.attcollation::regcollation::text,'public\.','','g') end||'|'||coalesce(nullif(a.attidentity::text,''),'<none>')||'|'||coalesce(nullif(a.attgenerated::text,''),'<none>')||'|'||a.attstorage::text,E'\n' order by c.relname collate "C",a.attnum,a.attname collate "C"),'')) h
 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts') and a.attnum>0 and not a.attisdropped and not (c.relname='posts' and a.attname in ('is_highlighted','highlighted_at'))
),
highlight_column_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||a.attname||'|'||regexp_replace(format_type(a.atttypid,a.atttypmod),'public\.','','g')||'|'||case when a.attnotnull then 't' else 'f' end||'|'||regexp_replace(coalesce(pg_get_expr(d.adbin,d.adrelid,true),''),'public\.','','g')||'|'||case when a.attcollation=0 then '-' else regexp_replace(a.attcollation::regcollation::text,'public\.','','g') end||'|'||coalesce(nullif(a.attidentity::text,''),'<none>')||'|'||coalesce(nullif(a.attgenerated::text,''),'<none>')||'|'||a.attstorage::text,E'\n' order by c.relname collate "C",a.attname collate "C"),'')) h
 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and c.relname='posts' and a.attname in ('is_highlighted','highlighted_at') and a.attnum>0 and not a.attisdropped
),
constraint_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||x.conname||'|'||x.contype::text||'|'||regexp_replace(pg_get_constraintdef(x.oid,true),'public\.','','g')||'|'||case when x.convalidated then 't' else 'f' end||'|'||case when x.condeferrable then 't' else 'f' end||'|'||case when x.condeferred then 't' else 'f' end,E'\n' order by c.relname collate "C",x.conname collate "C"),'')) h
 from pg_constraint x join pg_class c on c.oid=x.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
index_state as (
 select count(*)::int n,md5(coalesce(string_agg(t.relname||'|'||i.relname||'|'||regexp_replace(pg_get_indexdef(i.oid),'public\.','','g')||'|'||case when x.indisunique then 't' else 'f' end||'|'||case when x.indisprimary then 't' else 'f' end||'|'||case when x.indisvalid then 't' else 'f' end||'|'||case when x.indisready then 't' else 'f' end,E'\n' order by t.relname collate "C",i.relname collate "C"),'')) h
 from pg_index x join pg_class t on t.oid=x.indrelid join pg_class i on i.oid=x.indexrelid join pg_namespace n on n.oid=t.relnamespace where n.nspname='public' and t.relname in ('post_reactions','post_write_rate_limits','posts')
),
trigger_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||t.tgname||'|'||regexp_replace(pg_get_triggerdef(t.oid,true),'public\.','','g')||'|'||t.tgenabled::text,E'\n' order by c.relname collate "C",t.tgname collate "C"),'')) h
 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts') and not t.tgisinternal
),
policy_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||p.polname||'|'||(case p.polcmd when 'r' then 'SELECT' when 'a' then 'INSERT' when 'w' then 'UPDATE' when 'd' then 'DELETE' when '*' then 'ALL' end)||'|'||(case when p.polpermissive then 'PERMISSIVE' else 'RESTRICTIVE' end)||'|'||lower(coalesce((select array_agg(case when x=0 then 'public' else x::regrole::text end order by (case when x=0 then 'public' else x::regrole::text end) collate "C")::text from unnest(p.polroles) x),'{}'))||'|'||(case when p.polqual is null then '<null>' else lower(regexp_replace(regexp_replace(pg_get_expr(p.polqual,p.polrelid),'public\.','','g'),'[[:space:]]+','','g')) end)||'|'||(case when p.polwithcheck is null then '<null>' else lower(regexp_replace(regexp_replace(pg_get_expr(p.polwithcheck,p.polrelid),'public\.','','g'),'[[:space:]]+','','g')) end),E'\n' order by c.relname collate "C",p.polname collate "C"),'')) h
 from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
acl_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end)||'|'||a.privilege_type||'|'||case when a.is_grantable then 't' else 'f' end||'|'||a.grantor::regrole::text,E'\n' order by c.relname collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C",a.grantor::regrole::text collate "C"),'')) h
 from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
colacl_state as (
 select count(*)::int n from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute att on att.attrelid=c.oid cross join lateral aclexplode(att.attacl) a where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts') and att.attnum>0 and not att.attisdropped
),
publication_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||p.pubname,E'\n' order by c.relname collate "C",p.pubname collate "C"),'')) h from pg_publication_rel pr join pg_publication p on p.oid=pr.prpubid join pg_class c on c.oid=pr.prrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
wall_function_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'|'||p.proname||'|'||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||'|'||regexp_replace(pg_get_function_arguments(p.oid),'public\.','','g')||'|'||p.proowner::regrole::text||'|'||l.lanname||'|'||p.provolatile::text||'|'||case when p.prosecdef then 't' else 'f' end||'|'||case when p.proisstrict then 't' else 'f' end||'|'||case when p.proleakproof then 't' else 'f' end||'|'||p.proparallel::text||'|'||p.pronargdefaults||'|'||coalesce((select string_agg(case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by (case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end) collate "C") from unnest(coalesce(p.proconfig,array[]::text[])) cfg),'<none>')||'|'||regexp_replace(pg_get_function_result(p.oid),'public\.','','g')||'|'||md5(btrim(regexp_replace(p.prosrc,'[[:space:]]+',' ','g'))),E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname in ('admin_block_post_link_domain','admin_delete_notice_post','admin_delete_post','admin_flag_post_for_hero','admin_unblock_post_link_domain','admin_unflag_post_for_hero','clear_hero_on_author_ban','consume_post_write_rate_limit','create_post','current_user_can_read_post','current_user_can_read_post_author','current_user_can_read_post_reaction','delete_own_post','enforce_post_write_invariants','guard_post_reaction_identity','is_valid_post_reaction_code','normalize_post_link_domain','post_body_passes_link_blocklist','post_image_array_has_unique_values','post_images_belong_to_profile','remove_post_reaction','set_post_reaction','update_post','enforce_post_highlight_limit','toggle_post_highlight')
),
wall_acl_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'.'||p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||')|'||a.grantor::regrole::text||'|'||(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end)||'|'||a.privilege_type||'|'||case when a.is_grantable then 't' else 'f' end,E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C",a.grantor::regrole::text collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where n.nspname='public' and p.proname in ('admin_block_post_link_domain','admin_delete_notice_post','admin_delete_post','admin_flag_post_for_hero','admin_unblock_post_link_domain','admin_unflag_post_for_hero','clear_hero_on_author_ban','consume_post_write_rate_limit','create_post','current_user_can_read_post','current_user_can_read_post_author','current_user_can_read_post_reaction','delete_own_post','enforce_post_write_invariants','guard_post_reaction_identity','is_valid_post_reaction_code','normalize_post_link_domain','post_body_passes_link_blocklist','post_image_array_has_unique_values','post_images_belong_to_profile','remove_post_reaction','set_post_reaction','update_post','enforce_post_highlight_limit','toggle_post_highlight')
),
mp4a_function_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'|'||p.proname||'|'||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||'|'||regexp_replace(pg_get_function_arguments(p.oid),'public\.','','g')||'|'||p.proowner::regrole::text||'|'||l.lanname||'|'||p.provolatile::text||'|'||case when p.prosecdef then 't' else 'f' end||'|'||case when p.proisstrict then 't' else 'f' end||'|'||case when p.proleakproof then 't' else 'f' end||'|'||p.proparallel::text||'|'||p.pronargdefaults||'|'||coalesce((select string_agg(case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by (case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end) collate "C") from unnest(coalesce(p.proconfig,array[]::text[])) cfg),'<none>')||'|'||regexp_replace(pg_get_function_result(p.oid),'public\.','','g')||'|'||md5(btrim(regexp_replace(p.prosrc,'[[:space:]]+',' ','g'))),E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where (n.nspname='private' and p.proname='current_active_profile_id') or (n.nspname='public' and p.proname in ('current_active_profile_id','current_user_is_active_profile','current_user_is_active_unsuspended_profile'))
),
mp4a_acl_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'.'||p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||')|'||a.grantor::regrole::text||'|'||(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end)||'|'||a.privilege_type||'|'||case when a.is_grantable then 't' else 'f' end,E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C",a.grantor::regrole::text collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where (n.nspname='private' and p.proname='current_active_profile_id') or (n.nspname='public' and p.proname in ('current_active_profile_id','current_user_is_active_profile','current_user_is_active_unsuspended_profile'))
),
legacy_function_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'|'||p.proname||'|'||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||'|'||regexp_replace(pg_get_function_arguments(p.oid),'public\.','','g')||'|'||p.proowner::regrole::text||'|'||l.lanname||'|'||p.provolatile::text||'|'||case when p.prosecdef then 't' else 'f' end||'|'||case when p.proisstrict then 't' else 'f' end||'|'||case when p.proleakproof then 't' else 'f' end||'|'||p.proparallel::text||'|'||p.pronargdefaults||'|'||coalesce((select string_agg(case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by (case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end) collate "C") from unnest(coalesce(p.proconfig,array[]::text[])) cfg),'<none>')||'|'||regexp_replace(pg_get_function_result(p.oid),'public\.','','g')||'|'||md5(btrim(regexp_replace(p.prosrc,'[[:space:]]+',' ','g'))),E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname in ('create_additional_profile','current_user_is_banned','current_user_owns_profile','current_user_owns_unsuspended_profile')
),
legacy_acl_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'.'||p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||')|'||a.grantor::regrole::text||'|'||(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end)||'|'||a.privilege_type||'|'||case when a.is_grantable then 't' else 'f' end,E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C",a.grantor::regrole::text collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where n.nspname='public' and p.proname in ('create_additional_profile','current_user_is_banned','current_user_owns_profile','current_user_owns_unsuspended_profile')
),
manifest as (
 select r.n relation_n,r.h relation_h,c.n column_n,c.h column_h,hc.n highlight_column_n,hc.h highlight_column_h,co.n constraint_n,co.h constraint_h,i.n index_n,i.h index_h,t.n trigger_n,t.h trigger_h,p.n policy_n,p.h policy_h,a.n acl_n,a.h acl_h,ca.n colacl_n,pu.n publication_n,pu.h publication_h,wf.n wall_function_n,wf.h wall_function_h,wa.n wall_acl_n,wa.h wall_acl_h,mf.n mp4a_function_n,mf.h mp4a_function_h,ma.n mp4a_acl_n,ma.h mp4a_acl_h,lf.n legacy_function_n,lf.h legacy_function_h,la.n legacy_acl_n,la.h legacy_acl_h from relation_state r cross join column_state c cross join highlight_column_state hc cross join constraint_state co cross join index_state i cross join trigger_state t cross join policy_state p cross join acl_state a cross join colacl_state ca cross join publication_state pu cross join wall_function_state wf cross join wall_acl_state wa cross join mp4a_function_state mf cross join mp4a_acl_state ma cross join legacy_function_state lf cross join legacy_acl_state la
)

 select ((m.relation_n=3 and m.relation_h='896fc89a04d20b4a954675e4b6617c7d'
 and m.column_n=18 and m.column_h='7e21ce93ef5410cf8b1deddef17f3dfc' and m.highlight_column_n=2 and m.highlight_column_h='648cd29e2b2093884c479ee3a8680612'
 and m.constraint_n=16 and m.constraint_h='a75bda2d315fc51635e28c29d52cb5e6'
 and m.index_n=9 and m.index_h='64893d315dbb437172f40bcb1a1597be'
 and m.trigger_n=3 and m.trigger_h='b211f34861373d0f1ef7dbf072668e9b'
 and m.policy_n=2 and m.policy_h='4ed569e4742a87d96141c344ced1f5d8'
 and m.acl_n=(case when current_setting('server_version_num')::int>=170000 then 30 else 27 end)
 and m.acl_h=(case when current_setting('server_version_num')::int>=170000 then 'cc7fa3fcddd72c7542f85a0fb8fd10ef' else '51d2feec17ddf0a309e74ef4bc6e471b' end)
 and m.colacl_n=0 and m.publication_n=0 and m.publication_h='d41d8cd98f00b204e9800998ecf8427e'
 and m.wall_function_n=25 and m.wall_function_h='d98ebf15007d8fd14323ccdfcca77dd9'
 and m.wall_acl_n=44 and m.wall_acl_h='b684b58a31c39ae1c4326ebd10f1b1cd'
 and m.mp4a_function_n=4 and m.mp4a_function_h='094e79ae6b137952098334f53f54f695'
 and m.mp4a_acl_n=7 and m.mp4a_acl_h='1a9bc3c64d199fbfe7463dc80a3f7fb1'
 and m.legacy_function_n=4 and m.legacy_function_h='587f39a8031bb763f494e3612df94b73'
 and m.legacy_acl_n=8 and m.legacy_acl_h='6736d5d9cb627a2c79a7d2a84fb8f7d2') and (not exists((select rolname,rolsuper,rolinherit,rolbypassrls from pg_roles where rolname in ('anon','audit_readonly','authenticated','postgres','service_role')) except (values ('anon'::name,false,true,false),('audit_readonly'::name,false,false,false),('authenticated'::name,false,true,false),('postgres'::name,false,true,true),('service_role'::name,false,true,true))) and (select count(*) from pg_roles where rolname in ('anon','audit_readonly','authenticated','postgres','service_role'))=5)),((m.relation_n=3 and m.relation_h='896fc89a04d20b4a954675e4b6617c7d'
 and m.column_n=18 and m.column_h='7e21ce93ef5410cf8b1deddef17f3dfc' and m.highlight_column_n=0 and m.highlight_column_h='d41d8cd98f00b204e9800998ecf8427e'
 and m.constraint_n=15 and m.constraint_h='b0d239ef13d46d549eb86256aafb2635'
 and m.index_n=8 and m.index_h='de0159494a3da73e317dc15ee2d38a4e'
 and m.trigger_n=2 and m.trigger_h='b0e55d8bf75f44aed109a3f69b0d2a4e'
 and m.policy_n=2 and m.policy_h='4ed569e4742a87d96141c344ced1f5d8'
 and m.acl_n=(case when current_setting('server_version_num')::int>=170000 then 30 else 27 end)
 and m.acl_h=(case when current_setting('server_version_num')::int>=170000 then 'cc7fa3fcddd72c7542f85a0fb8fd10ef' else '51d2feec17ddf0a309e74ef4bc6e471b' end)
 and m.colacl_n=0 and m.publication_n=0 and m.publication_h='d41d8cd98f00b204e9800998ecf8427e'
 and m.wall_function_n=23 and m.wall_function_h='9ee1c2705f46e6c97892fc241344ebee'
 and m.wall_acl_n=41 and m.wall_acl_h='72c6cd1caebd622429534fb762bd103b'
 and m.mp4a_function_n=4 and m.mp4a_function_h='094e79ae6b137952098334f53f54f695'
 and m.mp4a_acl_n=7 and m.mp4a_acl_h='1a9bc3c64d199fbfe7463dc80a3f7fb1'
 and m.legacy_function_n=4 and m.legacy_function_h='587f39a8031bb763f494e3612df94b73'
 and m.legacy_acl_n=8 and m.legacy_acl_h='6736d5d9cb627a2c79a7d2a84fb8f7d2') and (not exists((select rolname,rolsuper,rolinherit,rolbypassrls from pg_roles where rolname in ('anon','audit_readonly','authenticated','postgres','service_role')) except (values ('anon'::name,false,true,false),('audit_readonly'::name,false,false,false),('authenticated'::name,false,true,false),('postgres'::name,false,true,true),('service_role'::name,false,true,true))) and (select count(*) from pg_roles where rolname in ('anon','audit_readonly','authenticated','postgres','service_role'))=5)) into source_ok,target_ok from manifest m;
 if target_ok then return; end if;
 if not source_ok then raise exception 'Wall highlights ROLLBACK refused: exact source/target manifest not found' using errcode='55000'; end if;
 execute 'drop function public.toggle_post_highlight(uuid, boolean)';
 execute 'drop trigger enforce_post_highlight_limit_trigger on public.posts';
 execute 'drop function public.enforce_post_highlight_limit()';
 execute 'drop index public.posts_profile_highlighted_id_idx';
 execute 'alter table public.posts drop constraint posts_highlight_state_check, drop column highlighted_at, drop column is_highlighted';
end
$transition$;
do $post$
declare ok boolean;
begin
 with
relation_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||c.relowner::regrole::text||'|'||c.relkind::text||'|'||c.relpersistence::text||'|'||case when c.relrowsecurity then 't' else 'f' end||'|'||case when c.relforcerowsecurity then 't' else 'f' end||'|'||c.relreplident::text,E'\n' order by c.relname collate "C"),'')) h
 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
column_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||a.attnum||'|'||a.attname||'|'||regexp_replace(format_type(a.atttypid,a.atttypmod),'public\.','','g')||'|'||case when a.attnotnull then 't' else 'f' end||'|'||regexp_replace(coalesce(pg_get_expr(d.adbin,d.adrelid,true),''),'public\.','','g')||'|'||case when a.attcollation=0 then '-' else regexp_replace(a.attcollation::regcollation::text,'public\.','','g') end||'|'||coalesce(nullif(a.attidentity::text,''),'<none>')||'|'||coalesce(nullif(a.attgenerated::text,''),'<none>')||'|'||a.attstorage::text,E'\n' order by c.relname collate "C",a.attnum,a.attname collate "C"),'')) h
 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts') and a.attnum>0 and not a.attisdropped and not (c.relname='posts' and a.attname in ('is_highlighted','highlighted_at'))
),
highlight_column_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||a.attname||'|'||regexp_replace(format_type(a.atttypid,a.atttypmod),'public\.','','g')||'|'||case when a.attnotnull then 't' else 'f' end||'|'||regexp_replace(coalesce(pg_get_expr(d.adbin,d.adrelid,true),''),'public\.','','g')||'|'||case when a.attcollation=0 then '-' else regexp_replace(a.attcollation::regcollation::text,'public\.','','g') end||'|'||coalesce(nullif(a.attidentity::text,''),'<none>')||'|'||coalesce(nullif(a.attgenerated::text,''),'<none>')||'|'||a.attstorage::text,E'\n' order by c.relname collate "C",a.attname collate "C"),'')) h
 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and c.relname='posts' and a.attname in ('is_highlighted','highlighted_at') and a.attnum>0 and not a.attisdropped
),
constraint_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||x.conname||'|'||x.contype::text||'|'||regexp_replace(pg_get_constraintdef(x.oid,true),'public\.','','g')||'|'||case when x.convalidated then 't' else 'f' end||'|'||case when x.condeferrable then 't' else 'f' end||'|'||case when x.condeferred then 't' else 'f' end,E'\n' order by c.relname collate "C",x.conname collate "C"),'')) h
 from pg_constraint x join pg_class c on c.oid=x.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
index_state as (
 select count(*)::int n,md5(coalesce(string_agg(t.relname||'|'||i.relname||'|'||regexp_replace(pg_get_indexdef(i.oid),'public\.','','g')||'|'||case when x.indisunique then 't' else 'f' end||'|'||case when x.indisprimary then 't' else 'f' end||'|'||case when x.indisvalid then 't' else 'f' end||'|'||case when x.indisready then 't' else 'f' end,E'\n' order by t.relname collate "C",i.relname collate "C"),'')) h
 from pg_index x join pg_class t on t.oid=x.indrelid join pg_class i on i.oid=x.indexrelid join pg_namespace n on n.oid=t.relnamespace where n.nspname='public' and t.relname in ('post_reactions','post_write_rate_limits','posts')
),
trigger_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||t.tgname||'|'||regexp_replace(pg_get_triggerdef(t.oid,true),'public\.','','g')||'|'||t.tgenabled::text,E'\n' order by c.relname collate "C",t.tgname collate "C"),'')) h
 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts') and not t.tgisinternal
),
policy_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||p.polname||'|'||(case p.polcmd when 'r' then 'SELECT' when 'a' then 'INSERT' when 'w' then 'UPDATE' when 'd' then 'DELETE' when '*' then 'ALL' end)||'|'||(case when p.polpermissive then 'PERMISSIVE' else 'RESTRICTIVE' end)||'|'||lower(coalesce((select array_agg(case when x=0 then 'public' else x::regrole::text end order by (case when x=0 then 'public' else x::regrole::text end) collate "C")::text from unnest(p.polroles) x),'{}'))||'|'||(case when p.polqual is null then '<null>' else lower(regexp_replace(regexp_replace(pg_get_expr(p.polqual,p.polrelid),'public\.','','g'),'[[:space:]]+','','g')) end)||'|'||(case when p.polwithcheck is null then '<null>' else lower(regexp_replace(regexp_replace(pg_get_expr(p.polwithcheck,p.polrelid),'public\.','','g'),'[[:space:]]+','','g')) end),E'\n' order by c.relname collate "C",p.polname collate "C"),'')) h
 from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
acl_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end)||'|'||a.privilege_type||'|'||case when a.is_grantable then 't' else 'f' end||'|'||a.grantor::regrole::text,E'\n' order by c.relname collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C",a.grantor::regrole::text collate "C"),'')) h
 from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
colacl_state as (
 select count(*)::int n from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute att on att.attrelid=c.oid cross join lateral aclexplode(att.attacl) a where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts') and att.attnum>0 and not att.attisdropped
),
publication_state as (
 select count(*)::int n,md5(coalesce(string_agg(c.relname||'|'||p.pubname,E'\n' order by c.relname collate "C",p.pubname collate "C"),'')) h from pg_publication_rel pr join pg_publication p on p.oid=pr.prpubid join pg_class c on c.oid=pr.prrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('post_reactions','post_write_rate_limits','posts')
),
wall_function_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'|'||p.proname||'|'||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||'|'||regexp_replace(pg_get_function_arguments(p.oid),'public\.','','g')||'|'||p.proowner::regrole::text||'|'||l.lanname||'|'||p.provolatile::text||'|'||case when p.prosecdef then 't' else 'f' end||'|'||case when p.proisstrict then 't' else 'f' end||'|'||case when p.proleakproof then 't' else 'f' end||'|'||p.proparallel::text||'|'||p.pronargdefaults||'|'||coalesce((select string_agg(case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by (case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end) collate "C") from unnest(coalesce(p.proconfig,array[]::text[])) cfg),'<none>')||'|'||regexp_replace(pg_get_function_result(p.oid),'public\.','','g')||'|'||md5(btrim(regexp_replace(p.prosrc,'[[:space:]]+',' ','g'))),E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname in ('admin_block_post_link_domain','admin_delete_notice_post','admin_delete_post','admin_flag_post_for_hero','admin_unblock_post_link_domain','admin_unflag_post_for_hero','clear_hero_on_author_ban','consume_post_write_rate_limit','create_post','current_user_can_read_post','current_user_can_read_post_author','current_user_can_read_post_reaction','delete_own_post','enforce_post_write_invariants','guard_post_reaction_identity','is_valid_post_reaction_code','normalize_post_link_domain','post_body_passes_link_blocklist','post_image_array_has_unique_values','post_images_belong_to_profile','remove_post_reaction','set_post_reaction','update_post','enforce_post_highlight_limit','toggle_post_highlight')
),
wall_acl_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'.'||p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||')|'||a.grantor::regrole::text||'|'||(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end)||'|'||a.privilege_type||'|'||case when a.is_grantable then 't' else 'f' end,E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C",a.grantor::regrole::text collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where n.nspname='public' and p.proname in ('admin_block_post_link_domain','admin_delete_notice_post','admin_delete_post','admin_flag_post_for_hero','admin_unblock_post_link_domain','admin_unflag_post_for_hero','clear_hero_on_author_ban','consume_post_write_rate_limit','create_post','current_user_can_read_post','current_user_can_read_post_author','current_user_can_read_post_reaction','delete_own_post','enforce_post_write_invariants','guard_post_reaction_identity','is_valid_post_reaction_code','normalize_post_link_domain','post_body_passes_link_blocklist','post_image_array_has_unique_values','post_images_belong_to_profile','remove_post_reaction','set_post_reaction','update_post','enforce_post_highlight_limit','toggle_post_highlight')
),
mp4a_function_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'|'||p.proname||'|'||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||'|'||regexp_replace(pg_get_function_arguments(p.oid),'public\.','','g')||'|'||p.proowner::regrole::text||'|'||l.lanname||'|'||p.provolatile::text||'|'||case when p.prosecdef then 't' else 'f' end||'|'||case when p.proisstrict then 't' else 'f' end||'|'||case when p.proleakproof then 't' else 'f' end||'|'||p.proparallel::text||'|'||p.pronargdefaults||'|'||coalesce((select string_agg(case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by (case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end) collate "C") from unnest(coalesce(p.proconfig,array[]::text[])) cfg),'<none>')||'|'||regexp_replace(pg_get_function_result(p.oid),'public\.','','g')||'|'||md5(btrim(regexp_replace(p.prosrc,'[[:space:]]+',' ','g'))),E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where (n.nspname='private' and p.proname='current_active_profile_id') or (n.nspname='public' and p.proname in ('current_active_profile_id','current_user_is_active_profile','current_user_is_active_unsuspended_profile'))
),
mp4a_acl_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'.'||p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||')|'||a.grantor::regrole::text||'|'||(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end)||'|'||a.privilege_type||'|'||case when a.is_grantable then 't' else 'f' end,E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C",a.grantor::regrole::text collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where (n.nspname='private' and p.proname='current_active_profile_id') or (n.nspname='public' and p.proname in ('current_active_profile_id','current_user_is_active_profile','current_user_is_active_unsuspended_profile'))
),
legacy_function_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'|'||p.proname||'|'||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||'|'||regexp_replace(pg_get_function_arguments(p.oid),'public\.','','g')||'|'||p.proowner::regrole::text||'|'||l.lanname||'|'||p.provolatile::text||'|'||case when p.prosecdef then 't' else 'f' end||'|'||case when p.proisstrict then 't' else 'f' end||'|'||case when p.proleakproof then 't' else 'f' end||'|'||p.proparallel::text||'|'||p.pronargdefaults||'|'||coalesce((select string_agg(case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end,',' order by (case when cfg in ('search_path=','search_path=""') then 'search_path=<empty>' else cfg end) collate "C") from unnest(coalesce(p.proconfig,array[]::text[])) cfg),'<none>')||'|'||regexp_replace(pg_get_function_result(p.oid),'public\.','','g')||'|'||md5(btrim(regexp_replace(p.prosrc,'[[:space:]]+',' ','g'))),E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and p.proname in ('create_additional_profile','current_user_is_banned','current_user_owns_profile','current_user_owns_unsuspended_profile')
),
legacy_acl_state as (
 select count(*)::int n,md5(coalesce(string_agg(n.nspname||'.'||p.proname||'('||regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g')||')|'||a.grantor::regrole::text||'|'||(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end)||'|'||a.privilege_type||'|'||case when a.is_grantable then 't' else 'f' end,E'\n' order by n.nspname collate "C",p.proname collate "C",regexp_replace(pg_get_function_identity_arguments(p.oid),'public\.','','g') collate "C",a.grantor::regrole::text collate "C",(case when a.grantee=0 then 'PUBLIC' else a.grantee::regrole::text end) collate "C",a.privilege_type collate "C"),'')) h from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where n.nspname='public' and p.proname in ('create_additional_profile','current_user_is_banned','current_user_owns_profile','current_user_owns_unsuspended_profile')
),
manifest as (
 select r.n relation_n,r.h relation_h,c.n column_n,c.h column_h,hc.n highlight_column_n,hc.h highlight_column_h,co.n constraint_n,co.h constraint_h,i.n index_n,i.h index_h,t.n trigger_n,t.h trigger_h,p.n policy_n,p.h policy_h,a.n acl_n,a.h acl_h,ca.n colacl_n,pu.n publication_n,pu.h publication_h,wf.n wall_function_n,wf.h wall_function_h,wa.n wall_acl_n,wa.h wall_acl_h,mf.n mp4a_function_n,mf.h mp4a_function_h,ma.n mp4a_acl_n,ma.h mp4a_acl_h,lf.n legacy_function_n,lf.h legacy_function_h,la.n legacy_acl_n,la.h legacy_acl_h from relation_state r cross join column_state c cross join highlight_column_state hc cross join constraint_state co cross join index_state i cross join trigger_state t cross join policy_state p cross join acl_state a cross join colacl_state ca cross join publication_state pu cross join wall_function_state wf cross join wall_acl_state wa cross join mp4a_function_state mf cross join mp4a_acl_state ma cross join legacy_function_state lf cross join legacy_acl_state la
)

 select ((m.relation_n=3 and m.relation_h='896fc89a04d20b4a954675e4b6617c7d'
 and m.column_n=18 and m.column_h='7e21ce93ef5410cf8b1deddef17f3dfc' and m.highlight_column_n=0 and m.highlight_column_h='d41d8cd98f00b204e9800998ecf8427e'
 and m.constraint_n=15 and m.constraint_h='b0d239ef13d46d549eb86256aafb2635'
 and m.index_n=8 and m.index_h='de0159494a3da73e317dc15ee2d38a4e'
 and m.trigger_n=2 and m.trigger_h='b0e55d8bf75f44aed109a3f69b0d2a4e'
 and m.policy_n=2 and m.policy_h='4ed569e4742a87d96141c344ced1f5d8'
 and m.acl_n=(case when current_setting('server_version_num')::int>=170000 then 30 else 27 end)
 and m.acl_h=(case when current_setting('server_version_num')::int>=170000 then 'cc7fa3fcddd72c7542f85a0fb8fd10ef' else '51d2feec17ddf0a309e74ef4bc6e471b' end)
 and m.colacl_n=0 and m.publication_n=0 and m.publication_h='d41d8cd98f00b204e9800998ecf8427e'
 and m.wall_function_n=23 and m.wall_function_h='9ee1c2705f46e6c97892fc241344ebee'
 and m.wall_acl_n=41 and m.wall_acl_h='72c6cd1caebd622429534fb762bd103b'
 and m.mp4a_function_n=4 and m.mp4a_function_h='094e79ae6b137952098334f53f54f695'
 and m.mp4a_acl_n=7 and m.mp4a_acl_h='1a9bc3c64d199fbfe7463dc80a3f7fb1'
 and m.legacy_function_n=4 and m.legacy_function_h='587f39a8031bb763f494e3612df94b73'
 and m.legacy_acl_n=8 and m.legacy_acl_h='6736d5d9cb627a2c79a7d2a84fb8f7d2') and (not exists((select rolname,rolsuper,rolinherit,rolbypassrls from pg_roles where rolname in ('anon','audit_readonly','authenticated','postgres','service_role')) except (values ('anon'::name,false,true,false),('audit_readonly'::name,false,false,false),('authenticated'::name,false,true,false),('postgres'::name,false,true,true),('service_role'::name,false,true,true))) and (select count(*) from pg_roles where rolname in ('anon','audit_readonly','authenticated','postgres','service_role'))=5)) into ok from manifest m;
 if not ok then raise exception 'Wall highlights ROLLBACK postcondition failed' using errcode='55000'; end if;
end
$post$;
commit;
