#!/usr/bin/env bash
set -euo pipefail
: "${HIGHLIGHTS_DB:?set HIGHLIGHTS_DB to a disposable MP4-D after-state database}"
HOST=${HIGHLIGHTS_HOST:-/tmp/mp4c2-sock}; PORT=${HIGHLIGHTS_PORT:-55442}; USER=${HIGHLIGHTS_USER:-postgres}; ADMIN=${HIGHLIGHTS_ADMIN_USER:-supabase_admin}
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd); LOG_DIR=${HIGHLIGHTS_LOG_DIR:-$(mktemp -d)}; mkdir -p "$LOG_DIR"; P=(psql -X -q -v ON_ERROR_STOP=1 -h "$HOST" -p "$PORT" -U "$USER" -d "$HIGHLIGHTS_DB")
FILES=("$ROOT/supabase/chunks/wall-highlights-preflight.sql" "$ROOT/supabase/chunks/wall-highlights-apply.sql" "$ROOT/supabase/chunks/wall-highlights-verify.sql" "$ROOT/supabase/chunks/wall-highlights-rollback.sql" "$ROOT/supabase/chunks/wall-highlights-disposable-runtime.sql" "$ROOT/supabase/chunks/wall-highlights-disposable-concurrency.sh" "$ROOT/supabase/chunks/wall-highlights-disposable-harness.sh")
sha256sum "${FILES[@]}" >"$LOG_DIR/start.sha256"
verdict(){ local f=$1 l=$2 h=${3:-no}; if [[ $h == yes ]]; then "${P[@]}" -At -c 'set search_path=pg_catalog' -f "$f" >"$LOG_DIR/$l.log"; else "${P[@]}" -At -f "$f" >"$LOG_DIR/$l.log"; fi; grep -q '|GO|' "$LOG_DIR/$l.log"; echo "$l=GO"; }
expect(){ local u=$1 d=$2 f=$3 state=$4 l=$5 rc; set +e; psql -X -q -v ON_ERROR_STOP=1 --set=VERBOSITY=verbose -h "$HOST" -p "$PORT" -U "$u" -d "$d" -f "$f" >"$LOG_DIR/$l.log" 2>&1; rc=$?; set -e; [[ $rc -ne 0 ]]; grep -q "$state" "$LOG_DIR/$l.log"; echo "$l=$state"; }
xmin(){ "${P[@]}" -At -c "select proname||'|'||xmin::text||'|'||ctid::text from pg_proc where oid in ('public.enforce_post_highlight_limit()'::regprocedure,'public.toggle_post_highlight(uuid,boolean)'::regprocedure) order by proname"; }
protected(){ "${P[@]}" -At -c "select md5(string_agg(pg_get_functiondef(p.oid)||'|'||p.proowner::regrole::text||'|'||coalesce(p.proacl::text,'<default>'),E'\\n' order by p.proname collate \"C\",pg_get_function_identity_arguments(p.oid) collate \"C\")) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('admin_block_post_link_domain','admin_delete_notice_post','admin_delete_post','admin_flag_post_for_hero','admin_unblock_post_link_domain','admin_unflag_post_for_hero','clear_hero_on_author_ban','consume_post_write_rate_limit','create_post','current_user_can_read_post','current_user_can_read_post_author','current_user_can_read_post_reaction','delete_own_post','enforce_post_write_invariants','guard_post_reaction_identity','is_valid_post_reaction_code','normalize_post_link_domain','post_body_passes_link_blocklist','post_image_array_has_unique_values','post_images_belong_to_profile','remove_post_reaction','set_post_reaction','update_post')"; }
"${P[@]}" -f "$ROOT/supabase/chunks/wall-highlights-rollback.sql" >"$LOG_DIR/initial-rollback.log"
verdict "$ROOT/supabase/chunks/wall-highlights-preflight.sql" preflight-default; verdict "$ROOT/supabase/chunks/wall-highlights-preflight.sql" preflight-hostile yes
protected_before=$(protected); "${P[@]}" -f "$ROOT/supabase/chunks/wall-highlights-apply.sql" >"$LOG_DIR/apply.log"; [[ $protected_before == "$(protected)" ]]; echo PROTECTED_WALL_HERO_BYTES=PASS; before=$(xmin); "${P[@]}" -f "$ROOT/supabase/chunks/wall-highlights-apply.sql" >"$LOG_DIR/apply-noop.log"; [[ $before == "$(xmin)" ]]; echo APPLY_NOOP=PASS
verdict "$ROOT/supabase/chunks/wall-highlights-verify.sql" verify-default; verdict "$ROOT/supabase/chunks/wall-highlights-verify.sql" verify-hostile yes
"${P[@]}" -f "$ROOT/supabase/chunks/wall-highlights-disposable-runtime.sql" >"$LOG_DIR/runtime.log" 2>&1; grep -q HIGHLIGHTS_BEHAVIOR=PASS "$LOG_DIR/runtime.log"; echo RUNTIME_MATRIX=PASS
HIGHLIGHTS_DB="$HIGHLIGHTS_DB" HIGHLIGHTS_HOST="$HOST" HIGHLIGHTS_PORT="$PORT" HIGHLIGHTS_USER="$USER" HIGHLIGHTS_ADMIN_USER="$ADMIN" HIGHLIGHTS_LOG_DIR="$LOG_DIR" bash "$ROOT/supabase/chunks/wall-highlights-disposable-concurrency.sh"
target="${HIGHLIGHTS_DB}_highlight_target_$$"; dropdb -h "$HOST" -p "$PORT" -U "$ADMIN" --if-exists "$target" >/dev/null; createdb -h "$HOST" -p "$PORT" -U "$ADMIN" -T "$HIGHLIGHTS_DB" -O "$USER" "$target"; psql -X -q -h "$HOST" -p "$PORT" -U "$ADMIN" -d "$target" -c 'alter function public.toggle_post_highlight(uuid,boolean) owner to supabase_admin' >/dev/null; expect "$USER" "$target" "$ROOT/supabase/chunks/wall-highlights-rollback.sql" 55000 target-drift-refused; dropdb -h "$HOST" -p "$PORT" -U "$ADMIN" "$target"; expect "$ADMIN" "$HIGHLIGHTS_DB" "$ROOT/supabase/chunks/wall-highlights-rollback.sql" 42501 target-wrong-owner-refused
"${P[@]}" -f "$ROOT/supabase/chunks/wall-highlights-rollback.sql" >"$LOG_DIR/rollback.log"; "${P[@]}" -f "$ROOT/supabase/chunks/wall-highlights-rollback.sql" >"$LOG_DIR/rollback-noop.log"; echo ROLLBACK_NOOP=PASS; verdict "$ROOT/supabase/chunks/wall-highlights-preflight.sql" restored-default; verdict "$ROOT/supabase/chunks/wall-highlights-preflight.sql" restored-hostile yes
source="${HIGHLIGHTS_DB}_highlight_source_$$"; dropdb -h "$HOST" -p "$PORT" -U "$ADMIN" --if-exists "$source" >/dev/null; createdb -h "$HOST" -p "$PORT" -U "$ADMIN" -T "$HIGHLIGHTS_DB" -O "$USER" "$source"; psql -X -q -h "$HOST" -p "$PORT" -U "$ADMIN" -d "$source" -c 'alter function public.create_post(uuid,text,text[],boolean) owner to supabase_admin' >/dev/null; expect "$USER" "$source" "$ROOT/supabase/chunks/wall-highlights-apply.sql" 55000 source-drift-refused; dropdb -h "$HOST" -p "$PORT" -U "$ADMIN" "$source"; expect "$ADMIN" "$HIGHLIGHTS_DB" "$ROOT/supabase/chunks/wall-highlights-apply.sql" 42501 source-wrong-owner-refused
"${P[@]}" -f "$ROOT/supabase/chunks/wall-highlights-apply.sql" >"$LOG_DIR/second-apply.log"; verdict "$ROOT/supabase/chunks/wall-highlights-verify.sql" second-verify-default; verdict "$ROOT/supabase/chunks/wall-highlights-verify.sql" second-verify-hostile yes; "${P[@]}" -f "$ROOT/supabase/chunks/wall-highlights-rollback.sql" >"$LOG_DIR/final-rollback.log"; verdict "$ROOT/supabase/chunks/wall-highlights-preflight.sql" final-restored-default; verdict "$ROOT/supabase/chunks/wall-highlights-preflight.sql" final-restored-hostile yes
sha256sum "${FILES[@]}" >"$LOG_DIR/end.sha256"; cmp "$LOG_DIR/start.sha256" "$LOG_DIR/end.sha256"; echo "WALL_HIGHLIGHTS_BOUND_LIFECYCLE=PASS logs=$LOG_DIR"
