import type { Listing, Profile } from "@/types/marketplace";

const image = (seed: string) => `https://picsum.photos/seed/${seed}/960/1200`;
const avatar = (seed: string) => `https://picsum.photos/seed/${seed}/320/320`;

export const mockProfiles: Profile[] = [
  {
    id: "profile-yacxilan",
    userId: "user-yacxilan",
    type: "artist",
    handle: "yacxilan",
    displayName: "Ya'cxilan",
    bio: "Festival fashion label focused on ritual silhouettes and handcrafted layers.",
    avatarUrl: avatar("seller-yacxilan"),
    location: "Berlin, Germany",
    isCreator: true,
    isVerified: true,
    socialLinks: { website: "https://yacxilan.com", instagram: "yacxilan", facebook: "yacxilan" },
    createdAt: "2026-02-10T12:00:00Z",
  },
  {
    id: "profile-darkmysterytribe",
    userId: "user-darkmysterytribe",
    type: "label",
    handle: "darkmysterytribe",
    displayName: "DarkMysteryTribe",
    bio: "Darkwear, UV reactive pieces, and high-energy psytrance apparel.",
    avatarUrl: avatar("seller-darkmysterytribe"),
    location: "Goa, India",
    isCreator: true,
    isVerified: true,
    socialLinks: { instagram: "darkmysterytribe", soundcloud: "darkmysterytribe" },
    createdAt: "2026-01-18T12:00:00Z",
  },
  {
    id: "profile-frequencylab",
    userId: "user-frequencylab",
    type: "artist",
    handle: "frequencylab",
    displayName: "FrequencyLab",
    bio: "Synth builder and sound tools for the global psy scene.",
    avatarUrl: avatar("seller-frequencylab"),
    location: "Lisbon, Portugal",
    isCreator: true,
    isVerified: false,
    socialLinks: { website: "https://frequencylab.pt", bandcamp: "frequencylab", soundcloud: "frequencylab" },
    createdAt: "2026-03-02T12:00:00Z",
  },
];

export const mockListings: Listing[] = [
  {
    id: "listing-fractal-hoodie",
    profileId: "profile-yacxilan",
    title: "Fractal Geometry Hoodie",
    description: "Heavyweight festival hoodie with geometric embroidery, oversized hood, and hidden pockets.",
    priceCents: 9900,
    condition: "new",
    category: "clothing",
    size: "M",
    tags: ["hoodie", "festival", "geometry"],
    shipsTo: ["DE", "NL", "WORLDWIDE"],
    images: [image("hoodie881"), image("hoodie882"), image("hoodie883"), image("hoodie884")],
    status: "active",
    isFeatured: true,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 182,
    createdAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "listing-sacred-tee",
    profileId: "profile-darkmysterytribe",
    title: "Sacred Geometry Tee",
    description: "Soft cotton tee with hand-screened sacred geometry print and relaxed fit.",
    priceCents: 4500,
    condition: "like_new",
    category: "clothing",
    size: "L",
    tags: ["tee", "print", "casual"],
    shipsTo: ["PT", "ES", "WORLDWIDE"],
    images: [image("tee7722")],
    status: "active",
    isFeatured: false,
    sellerHandle: "darkmysterytribe",
    sellerName: "DarkMysteryTribe",
    sellerLocation: "Goa, India",
    sellerRating: 5,
    viewCount: 94,
    createdAt: "2026-04-18T09:00:00Z",
  },
  {
    id: "listing-psydelic-jacket",
    profileId: "profile-yacxilan",
    title: "Psydelic Flow Jacket",
    description: "Structured outer layer with reflective accents and embroidered inner panels.",
    priceCents: 13500,
    condition: "good",
    category: "clothing",
    size: "L",
    tags: ["jacket", "outerwear", "reflective"],
    shipsTo: ["DE", "AT", "CH"],
    images: [image("jacket9933"), image("jacket9934"), image("jacket9935")],
    status: "active",
    isFeatured: true,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 133,
    createdAt: "2026-04-16T08:00:00Z",
  },
  {
    id: "listing-cosmic-cargo",
    profileId: "profile-darkmysterytribe",
    title: "Cosmic Cargo Pants",
    description: "Multi-pocket dancefloor cargos with adjustable hems and stretch waist.",
    priceCents: 7200,
    condition: "like_new",
    category: "clothing",
    size: "M/L",
    tags: ["pants", "cargo", "dancefloor"],
    shipsTo: ["WORLDWIDE"],
    images: [image("cargo1244")],
    status: "active",
    isFeatured: false,
    sellerHandle: "darkmysterytribe",
    sellerName: "DarkMysteryTribe",
    sellerLocation: "Goa, India",
    sellerRating: 5,
    viewCount: 76,
    createdAt: "2026-04-15T14:00:00Z",
  },
  {
    id: "listing-handpan",
    profileId: "profile-frequencylab",
    title: "Handpan Drum — D Minor",
    description: "Handcrafted handpan tuned for ambient and ceremony sessions.",
    priceCents: 98000,
    condition: "vintage",
    category: "gear",
    size: "One Size",
    tags: ["instrument", "handpan", "ceremony"],
    shipsTo: ["WORLDWIDE"],
    images: [image("handpan111")],
    status: "active",
    isFeatured: true,
    sellerHandle: "frequencylab",
    sellerName: "FrequencyLab",
    sellerLocation: "Lisbon, Portugal",
    sellerRating: 4.8,
    viewCount: 48,
    createdAt: "2026-04-12T16:00:00Z",
  },
  {
    id: "listing-amethyst-pendant",
    profileId: "profile-yacxilan",
    title: "Amethyst Pendant",
    description: "Wire-wrapped amethyst pendant for rituals, festivals, and everyday wear.",
    priceCents: 4800,
    condition: "new",
    category: "accessories",
    size: "One Size",
    tags: ["pendant", "amethyst", "jewellery"],
    shipsTo: ["WORLDWIDE"],
    images: [image("jewel8810")],
    status: "active",
    isFeatured: false,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 61,
    createdAt: "2026-04-11T08:30:00Z",
  },
  {
    id: "listing-tribal-wrap-dress",
    profileId: "profile-darkmysterytribe",
    title: "Tribal Wrap Dress",
    description: "Flowy wrap dress with tribal print panels, perfect for day-to-night festival wear.",
    priceCents: 8800,
    condition: "good",
    category: "clothing",
    size: "S/M",
    tags: ["dress", "wrap", "tribal"],
    shipsTo: ["WORLDWIDE"],
    images: [image("dress7755")],
    status: "active",
    isFeatured: false,
    sellerHandle: "darkmysterytribe",
    sellerName: "DarkMysteryTribe",
    sellerLocation: "Goa, India",
    sellerRating: 5,
    viewCount: 43,
    createdAt: "2026-04-10T11:00:00Z",
  },
  {
    id: "listing-uv-reactive-hoodie",
    profileId: "profile-yacxilan",
    title: "UV Reactive Hoodie",
    description: "Blacklight-activated hoodie with glowing geometric patterns for the dancefloor.",
    priceCents: 11500,
    condition: "new",
    category: "clothing",
    size: "L",
    tags: ["hoodie", "uv", "reactive"],
    shipsTo: ["DE", "NL", "WORLDWIDE"],
    images: [image("uvhood6")],
    status: "active",
    isFeatured: true,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 128,
    createdAt: "2026-04-09T09:00:00Z",
  },
  {
    id: "listing-festival-kimono",
    profileId: "profile-frequencylab",
    title: "Festival Kimono",
    description: "Light kimono with hand-painted mandala motifs. Great for layering in the crowd.",
    priceCents: 7800,
    condition: "worn",
    category: "clothing",
    size: "One Size",
    tags: ["dress", "kimono", "layering"],
    shipsTo: ["PT", "ES", "WORLDWIDE"],
    images: [image("kimono7")],
    status: "active",
    isFeatured: false,
    sellerHandle: "frequencylab",
    sellerName: "FrequencyLab",
    sellerLocation: "Lisbon, Portugal",
    sellerRating: 4.8,
    viewCount: 31,
    createdAt: "2026-04-08T14:00:00Z",
  },
  {
    id: "listing-mandala-tee",
    profileId: "profile-darkmysterytribe",
    title: "Mandala Print Tee",
    description: "Oversized unisex tee with large mandala screenprint on the back.",
    priceCents: 3800,
    condition: "good",
    category: "clothing",
    size: "XL",
    tags: ["tee", "mandala", "print"],
    shipsTo: ["WORLDWIDE"],
    images: [image("mandalatee8")],
    status: "active",
    isFeatured: false,
    sellerHandle: "darkmysterytribe",
    sellerName: "DarkMysteryTribe",
    sellerLocation: "Goa, India",
    sellerRating: 5,
    viewCount: 55,
    createdAt: "2026-04-07T10:00:00Z",
  },
  {
    id: "listing-flow-arts-leggings",
    profileId: "profile-yacxilan",
    title: "Flow Arts Leggings",
    description: "High-waist performance leggings with iridescent panels for flow and stage.",
    priceCents: 6500,
    condition: "like_new",
    category: "clothing",
    size: "S",
    tags: ["pants", "leggings", "flow"],
    shipsTo: ["DE", "AT", "CH", "NL"],
    images: [image("leggings9")],
    status: "active",
    isFeatured: true,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 89,
    createdAt: "2026-04-06T08:00:00Z",
  },
  {
    id: "listing-shaman-cloak",
    profileId: "profile-frequencylab",
    title: "Shaman Cloak",
    description: "Vintage ceremonial cloak with hand-sewn patches and deep ritual energy.",
    priceCents: 18500,
    condition: "vintage",
    category: "clothing",
    size: "One Size",
    tags: ["jacket", "cloak", "ceremony"],
    shipsTo: ["WORLDWIDE"],
    images: [image("cloak10")],
    status: "active",
    isFeatured: true,
    sellerHandle: "frequencylab",
    sellerName: "FrequencyLab",
    sellerLocation: "Lisbon, Portugal",
    sellerRating: 4.8,
    viewCount: 214,
    createdAt: "2026-04-05T16:00:00Z",
  },
  {
    id: "listing-rave-crop-top",
    profileId: "profile-darkmysterytribe",
    title: "Rave Crop Top",
    description: "Stretchy holographic crop top with strappy back detail.",
    priceCents: 3200,
    condition: "good",
    category: "clothing",
    size: "XS/S",
    tags: ["tee", "crop", "holographic"],
    shipsTo: ["WORLDWIDE"],
    images: [image("croptop11")],
    status: "active",
    isFeatured: false,
    sellerHandle: "darkmysterytribe",
    sellerName: "DarkMysteryTribe",
    sellerLocation: "Goa, India",
    sellerRating: 5,
    viewCount: 66,
    createdAt: "2026-04-04T12:00:00Z",
  },
  {
    id: "listing-patchwork-jacket",
    profileId: "profile-yacxilan",
    title: "Sacred Patchwork Jacket",
    description: "Handmade jacket assembled from vintage patchwork fabrics with embroidered details.",
    priceCents: 14800,
    condition: "new",
    category: "clothing",
    size: "M",
    tags: ["jacket", "patchwork", "handmade"],
    shipsTo: ["DE", "NL", "WORLDWIDE"],
    images: [image("patchjack12")],
    status: "active",
    isFeatured: true,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 101,
    createdAt: "2026-04-03T09:00:00Z",
  },
  {
    id: "listing-holographic-shorts",
    profileId: "profile-frequencylab",
    title: "Holographic Shorts",
    description: "Lightweight shorts with a full holographic finish — pure dancefloor material.",
    priceCents: 5500,
    condition: "like_new",
    category: "clothing",
    size: "M",
    tags: ["pants", "shorts", "holographic"],
    shipsTo: ["PT", "ES", "WORLDWIDE"],
    images: [image("shorts13")],
    status: "active",
    isFeatured: false,
    sellerHandle: "frequencylab",
    sellerName: "FrequencyLab",
    sellerLocation: "Lisbon, Portugal",
    sellerRating: 4.8,
    viewCount: 47,
    createdAt: "2026-04-02T14:00:00Z",
  },
  {
    id: "listing-boho-maxi-dress",
    profileId: "profile-darkmysterytribe",
    title: "Boho Maxi Dress",
    description: "Floor-length boho dress with lace trim and floral embroidery.",
    priceCents: 9600,
    condition: "good",
    category: "clothing",
    size: "S/M",
    tags: ["dress", "maxi", "boho"],
    shipsTo: ["WORLDWIDE"],
    images: [image("maxi14")],
    status: "active",
    isFeatured: false,
    sellerHandle: "darkmysterytribe",
    sellerName: "DarkMysteryTribe",
    sellerLocation: "Goa, India",
    sellerRating: 5,
    viewCount: 58,
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "listing-geometric-bomber",
    profileId: "profile-yacxilan",
    title: "Geometric Bomber",
    description: "Satin bomber jacket with geometric patchwork and embroidered back panel.",
    priceCents: 16000,
    condition: "new",
    category: "clothing",
    size: "L",
    tags: ["jacket", "bomber", "geometric"],
    shipsTo: ["DE", "NL", "AT", "WORLDWIDE"],
    images: [image("bomber15")],
    status: "active",
    isFeatured: true,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 93,
    createdAt: "2026-03-31T08:00:00Z",
  },
  {
    id: "listing-forest-spirit-hoodie",
    profileId: "profile-frequencylab",
    title: "Forest Spirit Hoodie",
    description: "Earth-toned hoodie with forest spirit embroidery and kangaroo pocket.",
    priceCents: 10800,
    condition: "like_new",
    category: "clothing",
    size: "M/L",
    tags: ["hoodie", "embroidery", "nature"],
    shipsTo: ["PT", "ES", "DE", "WORLDWIDE"],
    images: [image("forest16")],
    status: "active",
    isFeatured: false,
    sellerHandle: "frequencylab",
    sellerName: "FrequencyLab",
    sellerLocation: "Lisbon, Portugal",
    sellerRating: 4.8,
    viewCount: 72,
    createdAt: "2026-03-30T12:00:00Z",
  },
];
