import type { Listing, Profile } from "@/types/marketplace";

const image = (seed: string) => `https://picsum.photos/seed/${seed}/960/1200`;
const avatar = (seed: string) => `https://picsum.photos/seed/${seed}/320/320`;

export const mockProfiles: Profile[] = [
  {
    id: "profile-yacxilan",
    userId: "user-yacxilan",
    type: "artist",
    handle: "yacxilan",
    displayName: "Ya'cxilan",
    bio: "Festival fashion label focused on ritual silhouettes and handcrafted layers.",
    avatarUrl: avatar("seller-yacxilan"),
    location: "Berlin, Germany",
    isCreator: true,
    isVerified: true,
    createdAt: "2026-02-10T12:00:00Z",
  },
  {
    id: "profile-darkmysterytribe",
    userId: "user-darkmysterytribe",
    type: "label",
    handle: "darkmysterytribe",
    displayName: "DarkMysteryTribe",
    bio: "Darkwear, UV reactive pieces, and high-energy psytrance apparel.",
    avatarUrl: avatar("seller-darkmysterytribe"),
    location: "Goa, India",
    isCreator: true,
    isVerified: true,
    createdAt: "2026-01-18T12:00:00Z",
  },
  {
    id: "profile-frequencylab",
    userId: "user-frequencylab",
    type: "artist",
    handle: "frequencylab",
    displayName: "FrequencyLab",
    bio: "Synth builder and sound tools for the global psy scene.",
    avatarUrl: avatar("seller-frequencylab"),
    location: "Lisbon, Portugal",
    isCreator: true,
    isVerified: false,
    createdAt: "2026-03-02T12:00:00Z",
  },
];

export const mockListings: Listing[] = [
  {
    id: "listing-fractal-hoodie",
    profileId: "profile-yacxilan",
    title: "Fractal Geometry Hoodie",
    description: "Heavyweight festival hoodie with geometric embroidery, oversized hood, and hidden pockets.",
    priceCents: 9900,
    condition: "new",
    category: "clothing",
    size: "M",
    tags: ["hoodie", "festival", "geometry"],
    shipsTo: ["DE", "NL", "WORLDWIDE"],
    images: [image("hoodie881")],
    status: "active",
    isFeatured: true,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 182,
    createdAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "listing-sacred-tee",
    profileId: "profile-darkmysterytribe",
    title: "Sacred Geometry Tee",
    description: "Soft cotton tee with hand-screened sacred geometry print and relaxed fit.",
    priceCents: 4500,
    condition: "like_new",
    category: "clothing",
    size: "L",
    tags: ["tee", "print", "casual"],
    shipsTo: ["PT", "ES", "WORLDWIDE"],
    images: [image("tee7722")],
    status: "active",
    isFeatured: false,
    sellerHandle: "darkmysterytribe",
    sellerName: "DarkMysteryTribe",
    sellerLocation: "Goa, India",
    sellerRating: 5,
    viewCount: 94,
    createdAt: "2026-04-18T09:00:00Z",
  },
  {
    id: "listing-psydelic-jacket",
    profileId: "profile-yacxilan",
    title: "Psydelic Flow Jacket",
    description: "Structured outer layer with reflective accents and embroidered inner panels.",
    priceCents: 13500,
    condition: "good",
    category: "clothing",
    size: "L",
    tags: ["jacket", "outerwear", "reflective"],
    shipsTo: ["DE", "AT", "CH"],
    images: [image("jacket9933")],
    status: "active",
    isFeatured: true,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 133,
    createdAt: "2026-04-16T08:00:00Z",
  },
  {
    id: "listing-cosmic-cargo",
    profileId: "profile-darkmysterytribe",
    title: "Cosmic Cargo Pants",
    description: "Multi-pocket dancefloor cargos with adjustable hems and stretch waist.",
    priceCents: 7200,
    condition: "like_new",
    category: "clothing",
    size: "M/L",
    tags: ["pants", "cargo", "dancefloor"],
    shipsTo: ["WORLDWIDE"],
    images: [image("cargo1244")],
    status: "active",
    isFeatured: false,
    sellerHandle: "darkmysterytribe",
    sellerName: "DarkMysteryTribe",
    sellerLocation: "Goa, India",
    sellerRating: 5,
    viewCount: 76,
    createdAt: "2026-04-15T14:00:00Z",
  },
  {
    id: "listing-handpan",
    profileId: "profile-frequencylab",
    title: "Handpan Drum — D Minor",
    description: "Handcrafted handpan tuned for ambient and ceremony sessions.",
    priceCents: 98000,
    condition: "vintage",
    category: "gear",
    size: "One Size",
    tags: ["instrument", "handpan", "ceremony"],
    shipsTo: ["WORLDWIDE"],
    images: [image("handpan111")],
    status: "active",
    isFeatured: true,
    sellerHandle: "frequencylab",
    sellerName: "FrequencyLab",
    sellerLocation: "Lisbon, Portugal",
    sellerRating: 4.8,
    viewCount: 48,
    createdAt: "2026-04-12T16:00:00Z",
  },
  {
    id: "listing-amethyst-pendant",
    profileId: "profile-yacxilan",
    title: "Amethyst Pendant",
    description: "Wire-wrapped amethyst pendant for rituals, festivals, and everyday wear.",
    priceCents: 4800,
    condition: "new",
    category: "accessories",
    size: "One Size",
    tags: ["pendant", "amethyst", "jewellery"],
    shipsTo: ["WORLDWIDE"],
    images: [image("jewel8810")],
    status: "active",
    isFeatured: false,
    sellerHandle: "yacxilan",
    sellerName: "Ya'cxilan",
    sellerLocation: "Berlin, Germany",
    sellerRating: 4.9,
    viewCount: 61,
    createdAt: "2026-04-11T08:30:00Z",
  },
];
